from mcup.cli.ui.elements.collector import Collector, CollectorSection, CollectorInput, CollectorInputType
from mcup.core.utils.version import Version, LATEST_VERSION


class PaperCollector(Collector):
    def __init__(self):
        super().__init__()

        self.add_section(CollectorSection(
            "Paper - General Settings",
            [
                CollectorInput("effect-modifiers/strength", "COLLECTOR_PAPER_EFFECT_MODIFIERS_STRENGTH",
                               CollectorInputType.FLOAT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("effect-modifiers/weakness", "COLLECTOR_PAPER_EFFECT_MODIFIERS_WEAKNESS",
                               CollectorInputType.FLOAT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("stackable-buckets/lava", "COLLECTOR_PAPER_STACKABLE_BUCKETS_LAVA",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("stackable-buckets/water", "COLLECTOR_PAPER_STACKABLE_BUCKETS_WATER",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("stackable-buckets/milk", "COLLECTOR_PAPER_STACKABLE_BUCKETS_MILK",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("settings/baby-zombie-movement-speed",
                               "COLLECTOR_PAPER_SETTINGS_BABY_ZOMBIE_MOVEMENT_SPEED",
                               CollectorInputType.FLOAT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("settings/limit-player-interactions",
                               "COLLECTOR_PAPER_SETTINGS_LIMIT_PLAYER_INTERACTIONS",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("warnWhenSettingExcessiveVelocity",
                               "COLLECTOR_PAPER_WARN_WHEN_SETTING_EXCESSIVE_VELOCITY",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("data-value-allowed-items", "COLLECTOR_PAPER_DATA_VALUE_ALLOWED_ITEMS",
                               CollectorInputType.STRING, Version(1, 8, 8), LATEST_VERSION),
            ]
        ))
        self.add_section(CollectorSection(
            "Paper - World Settings",
            [
                CollectorInput("world-settings/default/verbose", "COLLECTOR_PAPER_WORLD_SETTINGS_VERBOSE",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/use-hopper-check",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_USE_HOPPER_CHECK", CollectorInputType.BOOL,
                               Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/disable-mood-sounds",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_DISABLE_MOOD_SOUNDS",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/fix-cannons", "COLLECTOR_PAPER_WORLD_SETTINGS_FIX_CANNONS",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/optimize-explosions",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_OPTIMIZE_EXPLOSIONS",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/mob-spawner-tick-rate",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_MOB_SPAWNER_TICK_RATE", CollectorInputType.INT,
                               Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/cache-chunk-maps",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_CACHE_CHUNK_MAPS", CollectorInputType.BOOL,
                               Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/squid-spawn-height/minimum",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_SQUID_SPAWN_HEIGHT_MINIMUM",
                               CollectorInputType.FLOAT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/squid-spawn-width/maximum",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_SQUID_SPAWN_WIDTH_MAXIMUM",
                               CollectorInputType.FLOAT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/tnt-explosion-volume",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_TNT_EXPLOSION_VOLUME",
                               CollectorInputType.FLOAT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/max-growth-height/cactus",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_MAX_GROWTH_HEIGHT_CACTUS",
                               CollectorInputType.INT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/max-growth-height/reeds",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_MAX_GROWTH_HEIGHT_REEDS",
                               CollectorInputType.INT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/fishing-time-range/MinimumTicks",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_FISHING_TIME_RANGE_MINIMUM_TICKS",
                               CollectorInputType.INT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/fishing-time-range/MaximumTicks",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_FISHING_TIME_RANGE_MAXIMUM_TICKS",
                               CollectorInputType.INT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/player-exhaustion/block-break",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_PLAYER_EXHAUSTION_BLOCK_BREAK",
                               CollectorInputType.FLOAT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/player-exhaustion/swimming",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_PLAYER_EXHAUSTION_SWIMMING",
                               CollectorInputType.FLOAT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/despawn-ranges/soft",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_DESPAWN_RANGES_SOFT",
                               CollectorInputType.INT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/despawn-ranges/hard",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_DESPAWN_RANGES_HARD",
                               CollectorInputType.INT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/remove-unloaded/enderpearls",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_REMOVE_UNLOADED_ENDERPEARLS",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/remove-unloaded/tnt-entities",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_REMOVE_UNLOADED_TNT_ENTITIES",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/remove-unloaded/falling-blocks",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_REMOVE_UNLOADED_FALLING_BLOCKS",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/game-mechanics/boats-drop-boats",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GAME_MECHANICS_BOATS_DROP_BOATS",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/game-mechanics/disable-player-crits",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GAME_MECHANICS_DISABLE_PLAYER_CRITS",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/game-mechanics/disable-chest-cat-detection",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GAME_MECHANICS_DISABLE_CHEST_CAT_DETECTION",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/game-mechanics/disable-end-credits",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GAME_MECHANICS_DISABLE_END_CREDITS",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/load-chunks/enderpearls",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_LOAD_CHUNKS_ENDERPEARLS",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/load-chunks/tnt-entities",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_LOAD_CHUNKS_TNT_ENTITIES",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/load-chunks/falling-blocks",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_LOAD_CHUNKS_FALLING_BLOCKS",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/fast-drain/lava",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_FAST_DRAIN_LAVA", CollectorInputType.BOOL,
                               Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/fast-drain/water",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_FAST_DRAIN_WATER", CollectorInputType.BOOL,
                               Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/lava-flow-speed/normal",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_LAVA_FLOW_SPEED_NORMAL",
                               CollectorInputType.INT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/lava-flow-speed/nether",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_LAVA_FLOW_SPEED_NETHER",
                               CollectorInputType.INT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/use-async-lighting",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_USE_ASYNC_LIGHTING",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/portal-search-radius",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_PORTAL_SEARCH_RADIUS",
                               CollectorInputType.INT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/disable-thunder",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_DISABLE_THUNDER",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/disable-ice-and-snow",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_DISABLE_ICE_AND_SNOW",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/tick-next-tick-list-cap",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_TICK_NEXT_TICK_LIST_CAP",
                               CollectorInputType.INT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/tick-next-tick-list-cap-ignores-redstone",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_TICK_NEXT_TICK_LIST_CAP_IGNORES_REDSTONE",
                               CollectorInputType.INT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/keep-spawn-loaded",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_KEEP_SPAWN_LOADED",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/generator-settings/canyon",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GENERATOR_SETTINGS_CANYON",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/generator-settings/caves",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GENERATOR_SETTINGS_CAVES",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/generator-settings/dungeon",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GENERATOR_SETTINGS_DUNGEON",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/generator-settings/fortress",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GENERATOR_SETTINGS_FORTRESS",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/generator-settings/mineshaft",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GENERATOR_SETTINGS_MINESHAFT",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/generator-settings/monument",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GENERATOR_SETTINGS_MONUMENT",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/generator-settings/stronghold",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GENERATOR_SETTINGS_STRONGHOLD",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/generator-settings/temple",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GENERATOR_SETTINGS_TEMPLE",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/generator-settings/village",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GENERATOR_SETTINGS_VILLAGE",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/generator-settings/flat-bedrock",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GENERATOR_SETTINGS_FLAT_BEDROCK",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/remove-invalid-mob-spawner-tile-entities",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_REMOVE_INVALID_MOB_SPAWNER_TILE_ENTITIES",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/player-blocking-damage-multiplier",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_PLAYER_BLOCKING_DAMAGE_MULTIPLIER",
                               CollectorInputType.FLOAT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/falling-block-height-nerf",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_FALLING_BLOCK_HEIGHT_NERF",
                               CollectorInputType.INT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/nether-ceiling-void-damage",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_NETHER_CEILING_VOID_DAMAGE",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/all-chunks-are-slime-chunks",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_ALL_CHUNKS_ARE_SLIME_CHUNKS",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/allow-undead-horse-leashing",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_ALLOW_UNDEAD_HORSE_LEASHING",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/container-update-tick-rate",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_CONTAINER_UPDATE_TICK_RATE",
                               CollectorInputType.INT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/falling-blocks-collide-with-signs",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_FALLING_BLOCKS_COLLIDE_WITH_SIGNS",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/allow-block-location-tab-completion",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_ALLOW_BLOCK_LOCATION_TAB_COMPLETION",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/disable-explosion-knockback",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_DISABLE_EXPLOSION_KNOCKBACK",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/tnt-entity-height-nerf",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_TNT_ENTITY_HEIGHT_NERF",
                               CollectorInputType.INT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/water-over-lava-flow-speed",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_WATER_OVER_LAVA_FLOW_SPEED",
                               CollectorInputType.INT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/disable-teleportation-suffocation-check",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_DISABLE_TELEPORTATION_SUFFOCATION_CHECK",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
            ],
            "Warning: It's recommended to leave all these settings as default"
        ))
