from mcup.cli.ui.elements.collector import Collector, CollectorSection, CollectorInputType, CollectorInput
from mcup.core.utils.version import Version, LATEST_VERSION


class PaperWorldDefaultsCollector(Collector):
    def __init__(self):
        super().__init__()

        self.add_section(CollectorSection(
            "Paper (World Defaults) - Anticheat",
            [
                CollectorInput("anticheat/anti-xray/enabled", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("anticheat/anti-xray/engine-mode", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("anticheat/anti-xray/hidden-blocks", "", CollectorInputType.STRING_LIST,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("anticheat/anti-xray/lava-obscures", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("anticheat/anti-xray/max-block-height", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("anticheat/anti-xray/replacement-blocks", "", CollectorInputType.STRING_LIST,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("anticheat/anti-xray/update-radius", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("anticheat/anti-xray/use-permission", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("anticheat/obfuscation/items/hide-durability", "", CollectorInputType.BOOL,
                               Version(1, 19), Version(1, 21, 3)),
                CollectorInput("anticheat/obfuscation/items/hide-itemmeta", "", CollectorInputType.BOOL,
                               Version(1, 19), Version(1, 21, 3)),
                CollectorInput("anticheat/obfuscation/items/hide-itemmeta-with-visual-effects", "",
                               CollectorInputType.BOOL, Version(1, 19, 2), Version(1, 21, 3))
            ]
        ))
        self.add_section(CollectorSection(
            "Paper (World Defaults) - Chunks",
            [
                CollectorInput("chunks/auto-save-interval", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("chunks/delay-chunk-unloads-by", "", CollectorInputType.STRING,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("chunks/entity-per-chunk-save-limit/arrow", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("chunks/entity-per-chunk-save-limit/ender_pearl", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("chunks/entity-per-chunk-save-limit/experience_orb", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("chunks/entity-per-chunk-save-limit/fireball", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("chunks/entity-per-chunk-save-limit/small_fireball", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("chunks/entity-per-chunk-save-limit/snowball", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("chunks/fixed-chunk-inhabited-time", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("chunks/flush-regions-on-save", "", CollectorInputType.BOOL,
                               Version(1, 19, 4), LATEST_VERSION),
                CollectorInput("chunks/max-auto-save-chunks-per-tick", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("chunks/prevent-moving-into-unloaded-chunks", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION)
            ]
        ))
        self.add_section(CollectorSection(
            "Paper (World Defaults) - Collisions",
            [
                CollectorInput("collisions/allow-player-cramming-damage", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("collisions/allow-vehicle-collisions", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("collisions/fix-climbing-bypassing-cramming-rule", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("collisions/max-entity-collisions", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("collisions/only-players-collide", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION)
            ]
        ))
        self.add_section(CollectorSection(
            "Paper (World Defaults) - Command Blocks",
            [
                CollectorInput("command-blocks/force-follow-perm-level", "", CollectorInputType.BOOL,
                               Version(1, 20, 4), LATEST_VERSION),
                CollectorInput("command-blocks/permissions-level", "", CollectorInputType.INT,
                               Version(1, 20, 4), LATEST_VERSION)
            ]
        ))
        self.add_section(CollectorSection(
            "Paper (World Defaults) - Behavior (Entities)",
            [
                CollectorInput("entities/behavior/allow-spider-world-border-climbing", "", CollectorInputType.BOOL,
                               Version(1, 19, 3), LATEST_VERSION),
                CollectorInput("entities/behavior/baby-zombie-movement-modifier", "", CollectorInputType.FLOAT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/cooldown-failed-beehive-releases", "", CollectorInputType.BOOL,
                               Version(1, 21, 4), LATEST_VERSION),
                CollectorInput("entities/behavior/disable-chest-cat-detection", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/disable-creeper-lingering-effect", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/disable-player-crits", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/door-breaking-difficulty/husk", "", CollectorInputType.STRING_LIST,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/door-breaking-difficulty/vindicator", "",
                               CollectorInputType.STRING_LIST, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/door-breaking-difficulty/zombie", "", CollectorInputType.STRING_LIST,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/door-breaking-difficulty/zombie_villager", "",
                               CollectorInputType.STRING_LIST, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/door-breaking-difficulty/zombified_piglin", "",
                               CollectorInputType.STRING_LIST, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/ender-dragons-death-always-places-dragon-egg", "",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/experience-merge-max-value", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/mobs-can-always-pick-up-loot/skeletons", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/mobs-can-always-pick-up-loot/zombies", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/nerf-pigmen-from-nether-portals", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/only-merge-items-horizontally", "", CollectorInputType.BOOL,
                               Version(1, 21, 1), LATEST_VERSION),
                CollectorInput("entities/behavior/parrots-are-unaffected-by-player-movement", "",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/phantoms-do-not-spawn-on-creative-players", "",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/phantoms-only-attack-insomniacs", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/phantoms-spawn-attempt-max-seconds", "", CollectorInputType.INT,
                               Version(1, 19, 2), LATEST_VERSION),
                CollectorInput("entities/behavior/phantoms-spawn-attempt-min-seconds", "", CollectorInputType.INT,
                               Version(1, 19, 2), LATEST_VERSION),
                CollectorInput("entities/behavior/piglins-guard-chests", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/pillager-patrols/disable", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/pillager-patrols/spawn-chance", "",
                               CollectorInputType.FLOAT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/pillager-patrols/spawn-delay/per-player", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/pillager-patrols/spawn-delay/ticks", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/pillager-patrols/start/day", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/pillager-patrols/start/per-player", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/player-insomnia-start-ticks", "", CollectorInputType.INT,
                               Version(1, 19, 2), LATEST_VERSION),
                CollectorInput("entities/behavior/should-remove-dragon", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/spawner-nerfed-mobs-should-jump", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/zombie-villager-infection-chance", "", CollectorInputType.FLOAT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/zombies-target-turtle-eggs", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION)
            ]
        ))
        self.add_section(CollectorSection(
            "Paper (World Defaults) - Armor Stands, Targeting, Markers, Mob Effects, Sniffers and Tracking Ranges "
            "(Entities)",
            [
                CollectorInput("entities/armor-stands/do-collision-entity-lookups", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/armor-stands/tick", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/entities-target-with-follow-range", "", CollectorInputType.BOOL,
                               Version(1, 19), Version(1, 21, 2)),
                CollectorInput("entities/markers/tick", "", CollectorInputType.BOOL,
                               Version(1, 19, 4), LATEST_VERSION),
                CollectorInput("entities/mob-effects/immune-to-wither-effect/wither", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/mob-effects/immune-to-wither-effect/wither-skeleton", "",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/mob-effects/spiders-immune-to-poison-effect", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/mob-effects/undead-immune-to-certain-effects", "", CollectorInputType.BOOL,
                               Version(1, 19), Version(1, 20, 4)),
                CollectorInput("entities/sniffer/boosted-hatch-time", "", CollectorInputType.INT,
                               Version(1, 20, 1), LATEST_VERSION),
                CollectorInput("entities/sniffer/hatch-time", "", CollectorInputType.INT,
                               Version(1, 20, 1), LATEST_VERSION),
                CollectorInput("entities/tracking-range-y/enabled", "", CollectorInputType.BOOL,
                               Version(1, 20, 1), LATEST_VERSION),
                CollectorInput("entities/tracking-range-y/animal", "", CollectorInputType.INT,
                               Version(1, 20, 1), LATEST_VERSION),
                CollectorInput("entities/tracking-range-y/display", "", CollectorInputType.INT,
                               Version(1, 20, 1), LATEST_VERSION),
                CollectorInput("entities/tracking-range-y/misc", "", CollectorInputType.INT,
                               Version(1, 20, 1), LATEST_VERSION),
                CollectorInput("entities/tracking-range-y/monster", "", CollectorInputType.INT,
                               Version(1, 20, 1), LATEST_VERSION),
                CollectorInput("entities/tracking-range-y/other", "", CollectorInputType.INT,
                               Version(1, 20, 1), LATEST_VERSION),
                CollectorInput("entities/tracking-range-y/player", "", CollectorInputType.INT,
                               Version(1, 20, 1), LATEST_VERSION),
            ]
        ))
        self.add_section(CollectorSection(
            "Paper (World Defaults) - Spawning (Entities)",
            [
                CollectorInput("entities/spawning/all-chunks-are-slime-chunks", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/alt-item-despawn-rate/enabled", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/alt-item-despawn-rate/items/cobblestone", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/count-all-mobs-for-spawning", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/creative-arrow-despawn-rate", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-range-shape", "", CollectorInputType.STRING,
                               Version(1, 21, 1), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/ambient/hard", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/ambient/soft", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/axolotls/hard", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/axolotls/soft", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/creature/hard", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/creature/soft", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/misc/hard", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/misc/soft", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/monster/hard", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/monster/soft", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/underground_water_creature/hard", "",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/underground_water_creature/soft", "",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/water_ambient/hard", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/water_ambient/soft", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/water_creature/hard", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/water_creature/soft", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-time/llama_spit", "", CollectorInputType.INT,
                               Version(1, 21, 3), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-time/snowball", "", CollectorInputType.INT,
                               Version(1, 21, 3), LATEST_VERSION),
                CollectorInput("entities/spawning/disable-mob-spawner-spawn-egg-transformation", "",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/duplicate-uuid/mode", "", CollectorInputType.STRING,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/duplicate-uuid/safe-regen-delete-range", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/filter-bad-tile-entity-nbt-from-falling-blocks", "",
                               CollectorInputType.BOOL, Version(1, 19, 3), LATEST_VERSION),
                CollectorInput("entities/spawning/filtered-entity-tag-nbt-paths", "", CollectorInputType.STRING_LIST,
                               Version(1, 19, 3), LATEST_VERSION),
                CollectorInput("entities/spawning/filter-nbt-data-from-spawn-eggs-and-related", "",
                               CollectorInputType.BOOL, Version(1, 19), Version(1, 19, 3)),
                CollectorInput("entities/spawning/iron-golems-can-spawn-in-air", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/monster-spawn-max-light-level", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/non-player-arrow-despawn-rate", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/per-player-mob-spawns", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/scan-for-legacy-ender-dragon", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/skeleton-horse-thunder-spawn-chance", "", CollectorInputType.FLOAT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/slime-spawn-height/slime-chunk/maximum", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/slime-spawn-height/surface-biome/maximum", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/slime-spawn-height/surface-biome/minimum", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/spawn-limits/ambient", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/spawn-limits/axolotls", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/spawn-limits/creature", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/spawn-limits/monster", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/spawn-limits/underground_water_creature", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/spawn-limits/water_ambient", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/spawn-limits/water_creature", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/ticks-per-spawn/ambient", "", CollectorInputType.INT,
                               Version(1, 20, 4), LATEST_VERSION),
                CollectorInput("entities/spawning/ticks-per-spawn/axolotls", "", CollectorInputType.INT,
                               Version(1, 20, 4), LATEST_VERSION),
                CollectorInput("entities/spawning/ticks-per-spawn/creature", "", CollectorInputType.INT,
                               Version(1, 20, 4), LATEST_VERSION),
                CollectorInput("entities/spawning/ticks-per-spawn/monster", "", CollectorInputType.INT,
                               Version(1, 20, 4), LATEST_VERSION),
                CollectorInput("entities/spawning/ticks-per-spawn/underground_water_creature", "",
                               CollectorInputType.INT, Version(1, 20, 4), LATEST_VERSION),
                CollectorInput("entities/spawning/ticks-per-spawn/water_ambient", "", CollectorInputType.INT,
                               Version(1, 20, 4), LATEST_VERSION),
                CollectorInput("entities/spawning/ticks-per-spawn/water_creature", "", CollectorInputType.INT,
                               Version(1, 20, 4), LATEST_VERSION),
                CollectorInput("entities/spawning/wandering-trader/spawn-chance-failure-increment", "",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/wandering-trader/spawn-chance-max", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/wandering-trader/spawn-chance-min", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/wandering-trader/spawn-day-length", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/wandering-trader/spawn-minute-length", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/wateranimal-spawn-height/maximum", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/wateranimal-spawn-height/minimum", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
            ]
        ))
        self.add_section(CollectorSection(
            "Paper (World Defaults) - Environment & Feature Seeds",
            [
                CollectorInput("environment/disable-explosion-knockback", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("environment/disable-ice-and-snow", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("environment/disable-teleportation-suffocation-check", "", CollectorInputType.BOOL,
                               Version(1, 19), Version(1, 21, 4)),
                CollectorInput("environment/disable-thunder", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("environment/fire-tick-delay", "", CollectorInputType.BOOL,
                               Version(1, 19, 2), LATEST_VERSION),
                CollectorInput("environment/frosted-ice/delay/max", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("environment/frosted-ice/delay/min", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("environment/frosted-ice/enabled", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("environment/generate-flat-bedrock", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("environment/locate-structures-outside-world-border", "", CollectorInputType.BOOL,
                               Version(1, 20, 4), LATEST_VERSION),
                CollectorInput("environment/max-block-ticks", "", CollectorInputType.INT,
                               Version(1, 20, 4), LATEST_VERSION),
                CollectorInput("environment/max-fluid-ticks", "", CollectorInputType.INT,
                               Version(1, 20, 4), LATEST_VERSION),
                CollectorInput("environment/nether-ceiling-void-damage-height", "", CollectorInputType.STRING,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("environment/optimize-explosions", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("environment/portal-create-radius", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("environment/portal-search-radius", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("environment/portal-search-vanilla-dimension-scaling", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("environment/treasure-maps/enabled", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("environment/treasure-maps/find-already-discovered/loot-tables", "",
                               CollectorInputType.STRING_LIST, Version(1, 19), LATEST_VERSION),
                CollectorInput("environment/treasure-maps/find-already-discovered/villager-trade", "",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("environment/void-damage-amount", "", CollectorInputType.INT,
                               Version(1, 21, 1), LATEST_VERSION),
                CollectorInput("environment/void-damage-min-build-height-offset", "", CollectorInputType.INT,
                               Version(1, 21, 1), LATEST_VERSION),
                CollectorInput("environment/water-over-lava-flow-speed", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("environment/feature-seeds/generate-random-seeds-for-all", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
            ]
        ))
        self.add_section(CollectorSection(
            "Paper (World Defaults) - Fishing Time Range, Fixes, Hoppers and Lootables",
            [
                CollectorInput("fishing-time-range/maximum", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("fishing-time-range/minimum", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("fixes/disable-unloaded-chunk-enderpearl-exploit", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("fixes/falling-block-height-nerf", "", CollectorInputType.STRING,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("fixes/fix-curing-zombie-villager-discount-exploit", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("fixes/fix-items-merging-through-walls", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("fixes/prevent-tnt-from-moving-in-water", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("fixes/split-overstacked-loot", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("fixes/tnt-entity-height-nerf", "", CollectorInputType.STRING,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("hoppers/cooldown-when-full", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("hoppers/disable-move-event", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("hoppers/ignore-occluding-blocks", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("lootables/auto-replenish", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("lootables/max-refills", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("lootables/refresh-max", "", CollectorInputType.STRING,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("lootables/refresh-min", "", CollectorInputType.STRING,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("lootables/reset-seed-on-fill", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("lootables/restrict-player-reloot", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("lootables/restrict-player-reloot-time", "", CollectorInputType.STRING,
                               Version(1, 20, 1), LATEST_VERSION),
                CollectorInput("lootables/retain-unlooted-shulker-box-loot-table-on-non-player-break", "",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
            ]
        ))
        self.add_section(CollectorSection(
            "Paper (World Defaults) - Maps, Max Growth Height and Misc",
            [
                CollectorInput("maps/item-frame-cursor-limit", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("maps/item-frame-cursor-update-interval", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("max-growth-height/bamboo/max", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("max-growth-height/bamboo/min", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("max-growth-height/cactus", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("max-growth-height/reeds", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("misc/alternate-current-update-order", "", CollectorInputType.STRING,
                               Version(1, 21, 1), LATEST_VERSION),
                CollectorInput("misc/disable-end-credits", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("misc/disable-relative-projectile-velocity", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("misc/disable-sprint-interruption-on-attack", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("misc/legacy-ender-pearl-behavior", "", CollectorInputType.BOOL,
                               Version(1, 21, 3), LATEST_VERSION),
                CollectorInput("misc/light-queue-size", "", CollectorInputType.INT,
                               Version(1, 19), Version(1, 21, 4)),
                CollectorInput("misc/max-leash-distance", "", CollectorInputType.STRING,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("misc/redstone-implementation", "", CollectorInputType.STRING,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("misc/shield-blocking-delay", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("misc/show-sign-click-command-failure-msgs-to-player", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("misc/update-pathfinding-on-block-update", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
            ]
        ))
        self.add_section(CollectorSection(
            "Paper (World Defaults) - Scoreboards, Spawn and Tick Rates",
            [
                CollectorInput("scoreboards/allow-non-player-entities-on-scoreboards", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("scoreboards/use-vanilla-world-scoreboard-name-coloring", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("spawn/allow-using-signs-inside-spawn-protection", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("spawn/keep-spawn-loaded", "", CollectorInputType.BOOL,
                               Version(1, 19), Version(1, 20, 4)),
                CollectorInput("spawn/keep-spawn-loaded-range", "", CollectorInputType.INT,
                               Version(1, 19), Version(1, 20, 4)),
                CollectorInput("tick-rates/behavior/villager/validatenearbypoi", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("tick-rates/container-update", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("tick-rates/dry-farmland", "", CollectorInputType.INT,
                               Version(1, 20, 2), LATEST_VERSION),
                CollectorInput("tick-rates/wet-farmland", "", CollectorInputType.INT,
                               Version(1, 20, 2), LATEST_VERSION),
                CollectorInput("tick-rates/grass-spread", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("tick-rates/mob-spawner", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("tick-rates/sensor/villager/secondarypoisensor", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
            ]
        ))
        self.add_section(CollectorSection(
            "Paper (World Defaults) - Unsupported Settings",
            [
                CollectorInput("unsupported-settings/disable-world-ticking-when-empty", "", CollectorInputType.BOOL,
                               Version(1, 20, 4), LATEST_VERSION),
                CollectorInput("unsupported-settings/fix-invulnerable-end-crystal-exploit", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION)
            ],
            "Warning: It's recommended to leave all these settings as default"
        ))
