from mcup.cli.ui.elements.collector import Collector, CollectorSection, CollectorInput, CollectorInputType, \
    CollectorInputMode
from mcup.core.utils.version import Version, LATEST_VERSION


class PaperCollector(Collector):
    def __init__(self):
        super().__init__("Paper")

        self.add_section(CollectorSection(
            "Messages",
            [
                CollectorInput("messages/kick/authentication-servers-down",
                               "COLLECTOR_PAPER_MESSAGES_KICK_AUTHENTICATION_SERVERS_DOWN",
                               CollectorInputType.STRING, CollectorInputMode.ADVANCED, Version(1, 12, 2),
                               LATEST_VERSION),
                CollectorInput("messages/kick/connection-throttle", "COLLECTOR_PAPER_MESSAGES_KICK_CONNECTION_THROTTLE",
                               CollectorInputType.STRING, CollectorInputMode.ADVANCED, Version(1, 13, 1),
                               LATEST_VERSION),
                CollectorInput("messages/kick/flying-player", "COLLECTOR_PAPER_MESSAGES_KICK_FLYING_PLAYER",
                               CollectorInputType.STRING, CollectorInputMode.ADVANCED, Version(1, 8, 8),
                               LATEST_VERSION),
                CollectorInput("messages/kick/flying-vehicle", "COLLECTOR_PAPER_MESSAGES_KICK_FLYING_VEHICLE",
                               CollectorInputType.STRING, CollectorInputMode.ADVANCED, Version(1, 8, 8),
                               LATEST_VERSION),
                CollectorInput("messages/no-permission", "COLLECTOR_PAPER_MESSAGES_NO_PERMISSION",
                               CollectorInputType.STRING, CollectorInputMode.ADVANCED, Version(1, 13, 2),
                               LATEST_VERSION),
            ]
        ))

        self.add_section(CollectorSection(
            "Timings",
            [
                CollectorInput("timings/enabled", "COLLECTOR_PAPER_TIMINGS_ENABLED",
                               CollectorInputType.BOOL, CollectorInputMode.BASIC, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("timings/verbose", "COLLECTOR_PAPER_TIMINGS_VERBOSE",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 11, 2), LATEST_VERSION),
                CollectorInput("timings/server-name", "COLLECTOR_PAPER_TIMINGS_SERVER_NAME",
                               CollectorInputType.STRING, CollectorInputMode.ADVANCED, Version(1, 14, 0),
                               LATEST_VERSION),
                CollectorInput("timings/server-name-privacy", "COLLECTOR_PAPER_TIMINGS_SERVER_NAME_PRIVACY",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("timings/history-interval", "COLLECTOR_PAPER_TIMINGS_HISTORY_INTERVAL",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("timings/history-length", "COLLECTOR_PAPER_TIMINGS_HISTORY_LENGTH",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("timings/url", "COLLECTOR_PAPER_TIMINGS_URL",
                               CollectorInputType.STRING, CollectorInputMode.ADVANCED, Version(1, 17, 1),
                               LATEST_VERSION),
            ]
        ))
        self.add_section(CollectorSection(
            "General Settings",
            [
                CollectorInput("effect-modifiers/strength", "COLLECTOR_PAPER_EFFECT_MODIFIERS_STRENGTH",
                               CollectorInputType.FLOAT, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("effect-modifiers/weakness", "COLLECTOR_PAPER_EFFECT_MODIFIERS_WEAKNESS",
                               CollectorInputType.FLOAT, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("stackable-buckets/lava", "COLLECTOR_PAPER_STACKABLE_BUCKETS_LAVA",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("stackable-buckets/water", "COLLECTOR_PAPER_STACKABLE_BUCKETS_WATER",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("stackable-buckets/milk", "COLLECTOR_PAPER_STACKABLE_BUCKETS_MILK",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("settings/baby-zombie-movement-speed",
                               "COLLECTOR_PAPER_SETTINGS_BABY_ZOMBIE_MOVEMENT_SPEED",
                               CollectorInputType.FLOAT, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("settings/limit-player-interactions",
                               "COLLECTOR_PAPER_SETTINGS_LIMIT_PLAYER_INTERACTIONS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("warnWhenSettingExcessiveVelocity",
                               "COLLECTOR_PAPER_WARN_WHEN_SETTING_EXCESSIVE_VELOCITY",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("data-value-allowed-items", "COLLECTOR_PAPER_DATA_VALUE_ALLOWED_ITEMS",
                               CollectorInputType.STRING, CollectorInputMode.ADVANCED, Version(1, 8, 8),
                               LATEST_VERSION),
            ] + [
                CollectorInput("settings/player-auto-save-rate", "COLLECTOR_PAPER_SETTINGS_PLAYER_AUTO_SAVE_RATE",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 11, 2), LATEST_VERSION),
                CollectorInput("settings/max-player-auto-save-per-tick",
                               "COLLECTOR_PAPER_SETTINGS_MAX_PLAYER_AUTO_SAVE_PER_TICK",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 12, 2), LATEST_VERSION),
                CollectorInput("settings/save-player-data", "COLLECTOR_PAPER_SETTINGS_SAVE_PLAYER_DATA",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 12, 2), LATEST_VERSION),
                CollectorInput("settings/book-size/page-max", "COLLECTOR_PAPER_SETTINGS_BOOK_SIZE_PAGE_MAX",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 12, 2), LATEST_VERSION),
                CollectorInput("settings/book-size/total-multiplier",
                               "COLLECTOR_PAPER_SETTINGS_BOOK_SIZE_TOTAL_MULTIPLIER",
                               CollectorInputType.FLOAT, CollectorInputMode.ADVANCED, Version(1, 12, 2),
                               LATEST_VERSION),
                CollectorInput("settings/spam-limiter/tab-spam-increment",
                               "COLLECTOR_PAPER_SETTINGS_SPAM_LIMITER_TAB_SPAM_INCREMENT",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 12, 2), LATEST_VERSION),
                CollectorInput("settings/spam-limiter/tab-spam-limit",
                               "COLLECTOR_PAPER_SETTINGS_SPAM_LIMITER_TAB_SPAM_LIMIT",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 12, 2), LATEST_VERSION),
                CollectorInput("settings/spam-limiter/recipe-spam-increment",
                               "COLLECTOR_PAPER_SETTINGS_SPAM_LIMITER_RECIPE_SPAM_INCREMENT",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 16, 4), LATEST_VERSION),
                CollectorInput("settings/spam-limiter/recipe-spam-limit",
                               "COLLECTOR_PAPER_SETTINGS_SPAM_LIMITER_RECIPE_SPAM_LIMIT",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 16, 4), LATEST_VERSION),
                CollectorInput("settings/watchdog/early-warning-every",
                               "COLLECTOR_PAPER_SETTINGS_WATCHDOG_EARLY_WARNING_EVERY",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 12, 2), LATEST_VERSION),
                CollectorInput("settings/watchdog/early-warning-delay",
                               "COLLECTOR_PAPER_SETTINGS_WATCHDOG_EARLY_WARNING_DELAY",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 12, 2), LATEST_VERSION),
                CollectorInput("settings/async-chunks/enable", "COLLECTOR_PAPER_SETTINGS_ASYNC_CHUNKS_ENABLE",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 13, 1), LATEST_VERSION),
                CollectorInput("settings/async-chunks/threads", "COLLECTOR_PAPER_SETTINGS_ASYNC_CHUNKS_THREADS",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 15, 2), LATEST_VERSION),
                CollectorInput("settings/velocity-support/enabled", "COLLECTOR_PAPER_SETTINGS_VELOCITY_SUPPORT_ENABLED",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 13, 1), LATEST_VERSION),
                CollectorInput("settings/velocity-support/online-mode",
                               "COLLECTOR_PAPER_SETTINGS_VELOCITY_SUPPORT_ONLINE_MODE",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 13, 1), LATEST_VERSION),
                CollectorInput("settings/velocity-support/secret", "COLLECTOR_PAPER_SETTINGS_VELOCITY_SUPPORT_SECRET",
                               CollectorInputType.STRING, CollectorInputMode.ADVANCED, Version(1, 13, 1),
                               LATEST_VERSION),
                CollectorInput("settings/console/enable-brigadier-highlighting",
                               "COLLECTOR_PAPER_SETTINGS_CONSOLE_ENABLE_BRIGADIER_HIGHLIGHTING",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 16, 5), LATEST_VERSION),
                CollectorInput("settings/console/enable-brigadier-completions",
                               "COLLECTOR_PAPER_SETTINGS_CONSOLE_ENABLE_BRIGADIER_COMPLETIONS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 16, 5), LATEST_VERSION),
                CollectorInput("settings/loggers/deobfuscate-stacktraces",
                               "COLLECTOR_PAPER_SETTINGS_LOGGERS_DEOBFUSCATE_STACKTRACES",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 17, 1), LATEST_VERSION),
                CollectorInput("settings/loggers/use-rgb-for-named-text-colors",
                               "COLLECTOR_PAPER_SETTINGS_LOGGERS_USE_RGB_FOR_NAMED_TEXT_COLORS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 18, 2), LATEST_VERSION),
                CollectorInput("settings/unsupported-settings/allow-piston-duplication",
                               "COLLECTOR_PAPER_SETTINGS_UNSUPPORTED_SETTINGS_ALLOW_PISTON_DUPLICATION",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 15, 2), LATEST_VERSION),
                CollectorInput("settings/unsupported-settings/perform-username-validation",
                               "COLLECTOR_PAPER_SETTINGS_UNSUPPORTED_SETTINGS_PERFORM_USERNAME_VALIDATION",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 17, 1), LATEST_VERSION),

                CollectorInput("settings/remove-invalid-statistics",
                               "COLLECTOR_PAPER_SETTINGS_REMOVE_INVALID_STATISTICS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 11, 2), LATEST_VERSION),
                CollectorInput("settings/suggest-player-names-when-null-tab-completions",
                               "COLLECTOR_PAPER_SETTINGS_SUGGEST_PLAYER_NAMES_WHEN_NULL_TAB_COMPLETIONS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 12, 2), LATEST_VERSION),
                CollectorInput("settings/use-alternative-luck-formula",
                               "COLLECTOR_PAPER_SETTINGS_USE_ALTERNATIVE_LUCK_FORMULA",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 12, 2), LATEST_VERSION),
                CollectorInput("settings/use-versioned-world", "COLLECTOR_PAPER_SETTINGS_USE_VERSIONED_WORLD",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 13, 0),
                               Version(1, 15, 0)),
                CollectorInput("settings/console-has-all-permissions",
                               "COLLECTOR_PAPER_SETTINGS_CONSOLE_HAS_ALL_PERMISSIONS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 15, 2), LATEST_VERSION),
                CollectorInput("settings/track-plugin-scoreboards", "COLLECTOR_PAPER_SETTINGS_TRACK_PLUGIN_SCOREBOARDS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 16, 3), LATEST_VERSION),
                CollectorInput("settings/fix-entity-position-desync",
                               "COLLECTOR_PAPER_SETTINGS_FIX_ENTITY_POSITION_DESYNC",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 16, 4), LATEST_VERSION),
                CollectorInput("settings/use-display-name-in-quit-message",
                               "COLLECTOR_PAPER_SETTINGS_USE_DISPLAY_NAME_IN_QUIT_MESSAGE",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 16, 5), LATEST_VERSION),
                CollectorInput("settings/lag-compensate-block-breaking",
                               "COLLECTOR_PAPER_SETTINGS_LAG_COMPENSATE_BLOCK_BREAKING",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 17, 1), LATEST_VERSION),
                CollectorInput("settings/log-player-ip-addresses", "COLLECTOR_PAPER_SETTINGS_LOG_PLAYER_IP_ADDRESSES",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 17, 1), LATEST_VERSION),
                CollectorInput("settings/send-full-pos-for-hard-colliding-entities",
                               "COLLECTOR_PAPER_SETTINGS_SEND_FULL_POS_FOR_HARD_COLLIDING_ENTITIES",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 17, 1), LATEST_VERSION),
                CollectorInput("settings/fix-target-selector-tag-completion",
                               "COLLECTOR_PAPER_SETTINGS_FIX_TARGET_SELECTOR_TAG_COMPLETION",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 18, 1), LATEST_VERSION),
                CollectorInput("settings/time-command-affects-all-worlds",
                               "COLLECTOR_PAPER_SETTINGS_TIME_COMMAND_AFFECTS_ALL_WORLDS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 18, 1), LATEST_VERSION),
                CollectorInput("settings/use-dimension-type-for-custom-spawners",
                               "COLLECTOR_PAPER_SETTINGS_USE_DIMENSION_TYPE_FOR_CUSTOM_SPAWNERS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 18, 1), LATEST_VERSION),
                CollectorInput("settings/proxy-protocol", "COLLECTOR_PAPER_SETTINGS_PROXY_PROTOCOL",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 18, 2), LATEST_VERSION),
                CollectorInput("settings/resolve-selectors-in-books",
                               "COLLECTOR_PAPER_SETTINGS_RESOLVE_SELECTORS_IN_BOOKS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 18, 2), LATEST_VERSION),
                CollectorInput("verbose", "COLLECTOR_PAPER_VERBOSE",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 11, 2), LATEST_VERSION),
            ]
        ))
        self.add_section(CollectorSection(
            "World Settings",
            [
                CollectorInput("world-settings/default/verbose", "COLLECTOR_PAPER_WORLD_SETTINGS_VERBOSE",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/use-hopper-check",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_USE_HOPPER_CHECK", CollectorInputType.BOOL,
                               CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/disable-mood-sounds",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_DISABLE_MOOD_SOUNDS",
                               CollectorInputType.BOOL, CollectorInputMode.BASIC, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/fix-cannons", "COLLECTOR_PAPER_WORLD_SETTINGS_FIX_CANNONS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/optimize-explosions",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_OPTIMIZE_EXPLOSIONS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/mob-spawner-tick-rate",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_MOB_SPAWNER_TICK_RATE", CollectorInputType.INT,
                               CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/cache-chunk-maps",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_CACHE_CHUNK_MAPS", CollectorInputType.BOOL,
                               CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/squid-spawn-height/minimum",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_SQUID_SPAWN_HEIGHT_MINIMUM",
                               CollectorInputType.FLOAT, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/squid-spawn-width/maximum",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_SQUID_SPAWN_WIDTH_MAXIMUM",
                               CollectorInputType.FLOAT, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/tnt-explosion-volume",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_TNT_EXPLOSION_VOLUME",
                               CollectorInputType.FLOAT, CollectorInputMode.BASIC, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/max-growth-height/cactus",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_MAX_GROWTH_HEIGHT_CACTUS",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/max-growth-height/reeds",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_MAX_GROWTH_HEIGHT_REEDS",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/fishing-time-range/MinimumTicks",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_FISHING_TIME_RANGE_MINIMUM_TICKS",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/fishing-time-range/MaximumTicks",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_FISHING_TIME_RANGE_MAXIMUM_TICKS",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/player-exhaustion/block-break",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_PLAYER_EXHAUSTION_BLOCK_BREAK",
                               CollectorInputType.FLOAT, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/player-exhaustion/swimming",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_PLAYER_EXHAUSTION_SWIMMING",
                               CollectorInputType.FLOAT, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/despawn-ranges/soft",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_DESPAWN_RANGES_SOFT",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/despawn-ranges/hard",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_DESPAWN_RANGES_HARD",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/remove-unloaded/enderpearls",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_REMOVE_UNLOADED_ENDERPEARLS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/remove-unloaded/tnt-entities",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_REMOVE_UNLOADED_TNT_ENTITIES",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/remove-unloaded/falling-blocks",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_REMOVE_UNLOADED_FALLING_BLOCKS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/game-mechanics/boats-drop-boats",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GAME_MECHANICS_BOATS_DROP_BOATS",
                               CollectorInputType.BOOL, CollectorInputMode.BASIC, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/game-mechanics/disable-player-crits",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GAME_MECHANICS_DISABLE_PLAYER_CRITS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/game-mechanics/disable-chest-cat-detection",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GAME_MECHANICS_DISABLE_CHEST_CAT_DETECTION",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/game-mechanics/disable-end-credits",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GAME_MECHANICS_DISABLE_END_CREDITS",
                               CollectorInputType.BOOL, CollectorInputMode.BASIC, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/load-chunks/enderpearls",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_LOAD_CHUNKS_ENDERPEARLS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/load-chunks/tnt-entities",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_LOAD_CHUNKS_TNT_ENTITIES",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/load-chunks/falling-blocks",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_LOAD_CHUNKS_FALLING_BLOCKS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/fast-drain/lava",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_FAST_DRAIN_LAVA", CollectorInputType.BOOL,
                               CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/fast-drain/water",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_FAST_DRAIN_WATER", CollectorInputType.BOOL,
                               CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/lava-flow-speed/normal",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_LAVA_FLOW_SPEED_NORMAL",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/lava-flow-speed/nether",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_LAVA_FLOW_SPEED_NETHER",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/use-async-lighting",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_USE_ASYNC_LIGHTING",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/portal-search-radius",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_PORTAL_SEARCH_RADIUS",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/disable-thunder",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_DISABLE_THUNDER",
                               CollectorInputType.BOOL, CollectorInputMode.BASIC, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/disable-ice-and-snow",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_DISABLE_ICE_AND_SNOW",
                               CollectorInputType.BOOL, CollectorInputMode.BASIC, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/tick-next-tick-list-cap",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_TICK_NEXT_TICK_LIST_CAP",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/tick-next-tick-list-cap-ignores-redstone",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_TICK_NEXT_TICK_LIST_CAP_IGNORES_REDSTONE",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/keep-spawn-loaded",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_KEEP_SPAWN_LOADED",
                               CollectorInputType.BOOL, CollectorInputMode.BASIC, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/generator-settings/canyon",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GENERATOR_SETTINGS_CANYON",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/generator-settings/caves",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GENERATOR_SETTINGS_CAVES",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/generator-settings/dungeon",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GENERATOR_SETTINGS_DUNGEON",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/generator-settings/fortress",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GENERATOR_SETTINGS_FORTRESS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/generator-settings/mineshaft",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GENERATOR_SETTINGS_MINESHAFT",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/generator-settings/monument",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GENERATOR_SETTINGS_MONUMENT",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/generator-settings/stronghold",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GENERATOR_SETTINGS_STRONGHOLD",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/generator-settings/temple",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GENERATOR_SETTINGS_TEMPLE",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/generator-settings/village",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GENERATOR_SETTINGS_VILLAGE",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/generator-settings/flat-bedrock",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GENERATOR_SETTINGS_FLAT_BEDROCK",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/remove-invalid-mob-spawner-tile-entities",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_REMOVE_INVALID_MOB_SPAWNER_TILE_ENTITIES",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/player-blocking-damage-multiplier",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_PLAYER_BLOCKING_DAMAGE_MULTIPLIER",
                               CollectorInputType.FLOAT, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/falling-block-height-nerf",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_FALLING_BLOCK_HEIGHT_NERF",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/nether-ceiling-void-damage",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_NETHER_CEILING_VOID_DAMAGE",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/all-chunks-are-slime-chunks",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_ALL_CHUNKS_ARE_SLIME_CHUNKS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/allow-undead-horse-leashing",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_ALLOW_UNDEAD_HORSE_LEASHING",
                               CollectorInputType.BOOL, CollectorInputMode.BASIC, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/container-update-tick-rate",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_CONTAINER_UPDATE_TICK_RATE",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/falling-blocks-collide-with-signs",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_FALLING_BLOCKS_COLLIDE_WITH_SIGNS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/allow-block-location-tab-completion",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_ALLOW_BLOCK_LOCATION_TAB_COMPLETION",
                               CollectorInputType.BOOL, CollectorInputMode.BASIC, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/disable-explosion-knockback",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_DISABLE_EXPLOSION_KNOCKBACK",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/tnt-entity-height-nerf",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_TNT_ENTITY_HEIGHT_NERF",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/water-over-lava-flow-speed",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_WATER_OVER_LAVA_FLOW_SPEED",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/disable-teleportation-suffocation-check",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_DISABLE_TELEPORTATION_SUFFOCATION_CHECK",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/anti-xray/enabled",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_ANTI_XRAY_ENABLED",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 12, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/anti-xray/engine-mode",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_ANTI_XRAY_ENGINE_MODE",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 12, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/anti-xray/chunk-edge-mode",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_ANTI_XRAY_CHUNK_EDGE_MODE",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 12, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/anti-xray/max-chunk-section-index",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_ANTI_XRAY_MAX_CHUNK_SECTION_INDEX",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 12, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/anti-xray/update-radius",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_ANTI_XRAY_UPDATE_RADIUS",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 12, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/anti-xray/lava-obscures",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_ANTI_XRAY_LAVA_OBSCURES",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 16, 3), LATEST_VERSION),
                CollectorInput("world-settings/default/anti-xray/use-permission",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_ANTI_XRAY_USE_PERMISSION",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 16, 4), LATEST_VERSION),
                CollectorInput("world-settings/default/anti-xray/max-block-height",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_ANTI_XRAY_MAX_BLOCK_HEIGHT",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 17, 1), LATEST_VERSION),

                CollectorInput("world-settings/default/armor-stands-do-collision-entity-lookups",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_ARMOR_STANDS_DO_COLLISION_ENTITY_LOOKUPS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 11, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/enable-treasure-maps",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_ENABLE_TREASURE_MAPS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 11, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/max-entity-collisions",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_MAX_ENTITY_COLLISIONS",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 11, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/skeleton-horse-thunder-spawn-chance",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_SKELETON_HORSE_THUNDER_SPAWN_CHANCE",
                               CollectorInputType.FLOAT, CollectorInputMode.ADVANCED, Version(1, 11, 2),
                               LATEST_VERSION),
                CollectorInput("world-settings/default/treasure-maps-return-already-discovered",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_TREASURE_MAPS_RETURN_ALREADY_DISCOVERED",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 11, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/armor-stands-tick",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_ARMOR_STANDS_TICK",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 12, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/bed-search-radius",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_BED_SEARCH_RADIUS",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 12, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/disable-creeper-lingering-effect",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_DISABLE_CREEPER_LINGERING_EFFECT",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 12, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/duplicate-uuid-resolver",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_DUPLICATE_UUID_RESOLVER",
                               CollectorInputType.STRING, CollectorInputMode.ADVANCED, Version(1, 12, 2),
                               LATEST_VERSION),
                CollectorInput("world-settings/default/duplicate-uuid-saferegen-delete-range",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_DUPLICATE_UUID_SAFEREGEN_DELETE_RANGE",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 12, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/experience-merge-max-value",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_EXPERIENCE_MERGE_MAX_VALUE",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 12, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/game-mechanics/allow-permanent-chunk-loaders",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GAME_MECHANICS_ALLOW_PERMANENT_CHUNK_LOADERS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 12, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/game-mechanics/disable-sprint-interruption-on-attack",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GAME_MECHANICS_DISABLE_SPRINT_INTERRUPTION_ON_ATTACK",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 12, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/game-mechanics/disable-unloaded-chunk-enderpearl-exploit",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GAME_MECHANICS_DISABLE_UNLOADED_CHUNK_ENDERPEARL_EXPLOIT",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 12, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/game-mechanics/scan-for-legacy-ender-dragon",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GAME_MECHANICS_SCAN_FOR_LEGACY_ENDER_DRAGON",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 12, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/game-mechanics/shield-blocking-delay",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GAME_MECHANICS_SHIELD_BLOCKING_DELAY",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 12, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/game-mechanics/village-sieges-enabled",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GAME_MECHANICS_VILLAGE_SIEGES_ENABLED",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 12, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/generator-settings/disable-extreme-hills-emeralds",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GENERATOR_SETTINGS_DISABLE_EXTREME_HILLS_EMERALDS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 12, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/generator-settings/disable-extreme-hills-monster-eggs",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GENERATOR_SETTINGS_DISABLE_EXTREME_HILLS_MONSTER_EGGS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 12, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/generator-settings/disable-mesa-additional-gold",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GENERATOR_SETTINGS_DISABLE_MESA_ADDITIONAL_GOLD",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 12, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/hopper/cooldown-when-full",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_HOPPER_COOLDOWN_WHEN_FULL",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 12, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/hopper/disable-move-event",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_HOPPER_DISABLE_MOVE_EVENT",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 12, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/max-chunk-gens-per-tick",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_MAX_CHUNK_GENS_PER_TICK",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 12, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/max-chunk-sends-per-tick",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_MAX_CHUNK_SENDS_PER_TICK",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 12, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/parrots-are-unaffected-by-player-movement",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_PARROTS_ARE_UNAFFECTED_BY_PLAYER_MOVEMENT",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 12, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/prevent-moving-into-unloaded-chunks",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_PREVENT_MOVING_INTO_UNLOADED_CHUNKS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 12, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/prevent-tnt-from-moving-in-water",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_PREVENT_TNT_FROM_MOVING_IN_WATER",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 12, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/skip-entity-ticking-in-chunks-scheduled-for-unload",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_SKIP_ENTITY_TICKING_IN_CHUNKS_SCHEDULED_FOR_UNLOAD",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 12, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/creative-arrow-despawn-rate",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_CREATIVE_ARROW_DESPAWN_RATE",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 13, 1), LATEST_VERSION),
                CollectorInput("world-settings/default/game-mechanics/villages-load-chunks",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GAME_MECHANICS_VILLAGES_LOAD_CHUNKS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 13, 1), LATEST_VERSION),
                CollectorInput("world-settings/default/lightning-strike-distance-limit/sound",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_LIGHTNING_STRIKE_DISTANCE_LIMIT_SOUND",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 13, 1), LATEST_VERSION),
                CollectorInput("world-settings/default/lightning-strike-distance-limit/impact-sound",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_LIGHTNING_STRIKE_DISTANCE_LIMIT_IMPACT_SOUND",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 13, 1), LATEST_VERSION),
                CollectorInput("world-settings/default/lightning-strike-distance-limit/flash",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_LIGHTNING_STRIKE_DISTANCE_LIMIT_FLASH",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 13, 1), LATEST_VERSION),
                CollectorInput("world-settings/default/count-all-mobs-for-spawning",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_COUNT_ALL_MOBS_FOR_SPAWNING",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 13, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/fixed-chunk-inhabited-time",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_FIXED_CHUNK_INHABITED_TIME",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 13, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/game-mechanics/disable-relative-projectile-velocity",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GAME_MECHANICS_DISABLE_RELATIVE_PROJECTILE_VELOCITY",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 13, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/nether-ceiling-void-damage-height",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_NETHER_CEILING_VOID_DAMAGE_HEIGHT",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 13, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/use-chunk-inhabited-timer",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_USE_CHUNK_INHABITED_TIMER",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 13, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/use-faster-eigencraft-redstone",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_USE_FASTER_EIGENCRAFT_REDSTONE",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 13, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/auto-save-interval",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_AUTO_SAVE_INTERVAL",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 14, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/max-auto-save-chunks-per-tick",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_MAX_AUTO_SAVE_CHUNKS_PER_TICK",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 14, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/alt-item-despawn-rate/enabled",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_ALT_ITEM_DESPAWN_RATE_ENABLED",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 14, 4), LATEST_VERSION),
                CollectorInput("world-settings/default/baby-zombie-movement-modifier",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_BABY_ZOMBIE_MOVEMENT_MODIFIER",
                               CollectorInputType.FLOAT, CollectorInputMode.ADVANCED, Version(1, 14, 4),
                               LATEST_VERSION),
                CollectorInput("world-settings/default/fix-zero-tick-instant-grow-farms",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_FIX_ZERO_TICK_INSTANT_GROW_FARMS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 14, 4), LATEST_VERSION),
                CollectorInput("world-settings/default/game-mechanics/disable-pillager-patrols",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GAME_MECHANICS_DISABLE_PILLAGER_PATROLS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 14, 4), LATEST_VERSION),
                CollectorInput("world-settings/default/per-player-mob-spawns",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_PER_PLAYER_MOB_SPAWNS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 14, 4), LATEST_VERSION),
                CollectorInput("world-settings/default/entities-target-with-follow-range",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_ENTITIES_TARGET_WITH_FOLLOW_RANGE",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 15, 1), LATEST_VERSION),
                CollectorInput("world-settings/default/portal-create-radius",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_PORTAL_CREATE_RADIUS",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 15, 1), LATEST_VERSION),
                CollectorInput("world-settings/default/delay-chunk-unloads-by",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_DELAY_CHUNK_UNLOADS_BY",
                               CollectorInputType.STRING, CollectorInputMode.ADVANCED, Version(1, 15, 2),
                               LATEST_VERSION),
                CollectorInput("world-settings/default/game-mechanics/nerf-pigmen-from-nether-portals",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GAME_MECHANICS_NERF_PIGMEN_FROM_NETHER_PORTALS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 15, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/game-mechanics/pillager-patrols/spawn-chance",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GAME_MECHANICS_PILLAGER_PATROLS_SPAWN_CHANCE",
                               CollectorInputType.FLOAT, CollectorInputMode.ADVANCED, Version(1, 15, 2),
                               LATEST_VERSION),
                CollectorInput("world-settings/default/iron-golems-can-spawn-in-air",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_IRON_GOLEMS_CAN_SPAWN_IN_AIR",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 15, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/light-queue-size",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_LIGHT_QUEUE_SIZE",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 15, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/phantoms-do-not-spawn-on-creative-players",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_PHANTOMS_DO_NOT_SPAWN_ON_CREATIVE_PLAYERS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 15, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/phantoms-only-attack-insomniacs",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_PHANTOMS_ONLY_ATTACK_INSOMNIACS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 15, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/seed-based-feature-search",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_SEED_BASED_FEATURE_SEARCH",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 15, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/viewdistances/no-tick-view-distance",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_VIEWDISTANCES_NO_TICK_VIEW_DISTANCE",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 15, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/zombie-villager-infection-chance",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_ZOMBIE_VILLAGER_INFECTION_CHANCE",
                               CollectorInputType.FLOAT, CollectorInputMode.ADVANCED, Version(1, 15, 2),
                               LATEST_VERSION),
                CollectorInput("world-settings/default/zombies-target-turtle-eggs",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_ZOMBIES_TARGET_TURTLE_EGGS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 16, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/fix-climbing-bypassing-cramming-rule",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_FIX_CLIMBING_BYPASSING_CRAMMING_RULE",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 16, 4), LATEST_VERSION),
                CollectorInput("world-settings/default/game-mechanics/disable-mob-spawner-spawn-egg-transformation",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GAME_MECHANICS_DISABLE_MOB_SPAWNER_SPAWN_EGG_TRANSFORMATION",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 16, 4), LATEST_VERSION),
                CollectorInput("world-settings/default/game-mechanics/fix-curing-zombie-villager-discount-exploit",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_GAME_MECHANICS_FIX_CURING_ZOMBIE_VILLAGER_DISCOUNT_EXPLOIT",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 16, 4), LATEST_VERSION),
                CollectorInput("world-settings/default/max-growth-height/bamboo/max",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_MAX_GROWTH_HEIGHT_BAMBOO_MAX",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 16, 4), LATEST_VERSION),
                CollectorInput("world-settings/default/max-growth-height/bamboo/min",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_MAX_GROWTH_HEIGHT_BAMBOO_MIN",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 16, 4), LATEST_VERSION),
                CollectorInput("world-settings/default/portal-search-vanilla-dimension-scaling",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_PORTAL_SEARCH_VANILLA_DIMENSION_SCALING",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 16, 4), LATEST_VERSION),
                CollectorInput("world-settings/default/should-remove-dragon",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_SHOULD_REMOVE_DRAGON",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 16, 4), LATEST_VERSION),
                CollectorInput("world-settings/default/allow-using-signs-inside-spawn-protection",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_ALLOW_USING_SIGNS_INSIDE_SPAWN_PROTECTION",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 16, 5), LATEST_VERSION),
                CollectorInput("world-settings/default/allow-vehicle-collisions",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_ALLOW_VEHICLE_COLLISIONS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 16, 5), LATEST_VERSION),
                CollectorInput("world-settings/default/ender-dragons-death-always-places-dragon-egg",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_ENDER_DRAGONS_DEATH_ALWAYS_PLACES_DRAGON_EGG",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 16, 5), LATEST_VERSION),
                CollectorInput("world-settings/default/fix-items-merging-through-walls",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_FIX_ITEMS_MERGING_THROUGH_WALLS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 16, 5), LATEST_VERSION),
                CollectorInput("world-settings/default/fix-wither-targeting-bug",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_FIX_WITHER_TARGETING_BUG",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 16, 5), LATEST_VERSION),
                CollectorInput("world-settings/default/map-item-frame-cursor-limit",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_MAP_ITEM_FRAME_CURSOR_LIMIT",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 16, 5), LATEST_VERSION),
                CollectorInput("world-settings/default/max-leash-distance",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_MAX_LEASH_DISTANCE",
                               CollectorInputType.FLOAT, CollectorInputMode.ADVANCED, Version(1, 16, 5),
                               LATEST_VERSION),
                CollectorInput("world-settings/default/only-players-collide",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_ONLY_PLAYERS_COLLIDE",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 16, 5), LATEST_VERSION),
                CollectorInput("world-settings/default/seed-based-feature-search-loads-chunks",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_SEED_BASED_FEATURE_SEARCH_LOADS_CHUNKS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 16, 5), LATEST_VERSION),
                CollectorInput("world-settings/default/show-sign-click-command-failure-msgs-to-player",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_SHOW_SIGN_CLICK_COMMAND_FAILURE_MSGS_TO_PLAYER",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 16, 5), LATEST_VERSION),
                CollectorInput("world-settings/default/update-pathfinding-on-block-update",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_UPDATE_PATHFINDING_ON_BLOCK_UPDATE",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 16, 5), LATEST_VERSION),
                CollectorInput("world-settings/default/allow-player-cramming-damage",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_ALLOW_PLAYER_CRAMMING_DAMAGE",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 17, 1), LATEST_VERSION),
                CollectorInput("world-settings/default/feature-seeds/generate-random-seeds-for-all",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_FEATURE_SEEDS_GENERATE_RANDOM_SEEDS_FOR_ALL",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 17, 1), LATEST_VERSION),
                CollectorInput("world-settings/default/hopper/ignore-occluding-blocks",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_HOPPER_IGNORE_OCCLUDING_BLOCKS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 17, 1), LATEST_VERSION),
                CollectorInput("world-settings/default/map-item-frame-cursor-update-interval",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_MAP_ITEM_FRAME_CURSOR_UPDATE_INTERVAL",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 17, 1), LATEST_VERSION),
                CollectorInput("world-settings/default/mob-effects/undead-immune-to-certain-effects",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_MOB_EFFECTS_UNDEAD_IMMUNE_TO_CERTAIN_EFFECTS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 17, 1), LATEST_VERSION),
                CollectorInput("world-settings/default/mob-effects/spiders-immune-to-poison-effect",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_MOB_EFFECTS_SPIDERS_IMMUNE_TO_POISON_EFFECT",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 17, 1), LATEST_VERSION),
                CollectorInput("world-settings/default/mob-effects/immune-to-wither-effect/wither",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_MOB_EFFECTS_IMMUNE_TO_WITHER_EFFECT_WITHER",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 17, 1), LATEST_VERSION),
                CollectorInput("world-settings/default/mob-effects/immune-to-wither-effect/wither-skeleton",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_MOB_EFFECTS_IMMUNE_TO_WITHER_EFFECT_WITHER_SKELETON",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 17, 1), LATEST_VERSION),
                CollectorInput("world-settings/default/piglins-guard-chests",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_PIGLINS_GUARD_CHESTS",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 17, 1), LATEST_VERSION),
                CollectorInput("world-settings/default/split-overstacked-loot",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_SPLIT_OVERSTACKED_LOOT",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 17, 1), LATEST_VERSION),
                CollectorInput("world-settings/default/anticheat/obfuscation/items/hide-itemmeta",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_ANTICHEAT_OBFUSCATION_ITEMS_HIDE_ITEMMETA",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 18, 1), LATEST_VERSION),
                CollectorInput("world-settings/default/anticheat/obfuscation/items/hide-durability",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_ANTICHEAT_OBFUSCATION_ITEMS_HIDE_DURABILITY",
                               CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 18, 1), LATEST_VERSION),
                CollectorInput("world-settings/default/monster-spawn-max-light-level",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_MONSTER_SPAWN_MAX_LIGHT_LEVEL",
                               CollectorInputType.INT, CollectorInputMode.ADVANCED, Version(1, 18, 1), LATEST_VERSION),
                CollectorInput("world-settings/default/slime-spawn-height/swamp-biome/maximum",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_SLIME_SPAWN_HEIGHT_SWAMP_BIOME_MAXIMUM",
                               CollectorInputType.FLOAT, CollectorInputMode.ADVANCED, Version(1, 18, 1),
                               LATEST_VERSION),
                CollectorInput("world-settings/default/slime-spawn-height/swamp-biome/minimum",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_SLIME_SPAWN_HEIGHT_SWAMP_BIOME_MINIMUM",
                               CollectorInputType.FLOAT, CollectorInputMode.ADVANCED, Version(1, 18, 1),
                               LATEST_VERSION),
                CollectorInput("world-settings/default/slime-spawn-height/slime-chunk/maximum",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_SLIME_SPAWN_HEIGHT_SLIME_CHUNK_MAXIMUM",
                               CollectorInputType.FLOAT, CollectorInputMode.ADVANCED, Version(1, 18, 1),
                               LATEST_VERSION),
                CollectorInput("world-settings/default/wateranimal-spawn-height/maximum",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_WATERANIMAL_SPAWN_HEIGHT_MAXIMUM",
                               CollectorInputType.STRING, CollectorInputMode.ADVANCED, Version(1, 18, 1),
                               LATEST_VERSION),
                CollectorInput("world-settings/default/wateranimal-spawn-height/minimum",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_WATERANIMAL_SPAWN_HEIGHT_MINIMUM",
                               CollectorInputType.STRING, CollectorInputMode.ADVANCED, Version(1, 18, 1),
                               LATEST_VERSION),
                CollectorInput("world-settings/default/redstone-implementation",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_REDSTONE_IMPLEMENTATION",
                               CollectorInputType.STRING, CollectorInputMode.ADVANCED, Version(1, 18, 2),
                               LATEST_VERSION),
                CollectorInput(
                    "world-settings/default/treasure-maps-find-already-discovered/villager-trade",
                    "COLLECTOR_PAPER_WORLD_SETTINGS_TREASURE_MAPS_FIND_ALREADY_DISCOVERED_VILLAGER_TRADE",
                    CollectorInputType.BOOL, CollectorInputMode.ADVANCED, Version(1, 18, 2), LATEST_VERSION),
                CollectorInput("world-settings/default/treasure-maps-find-already-discovered/loot-tables",
                               "COLLECTOR_PAPER_WORLD_SETTINGS_TREASURE_MAPS_FIND_ALREADY_DISCOVERED_LOOT_TABLES",
                               CollectorInputType.STRING, CollectorInputMode.ADVANCED, Version(1, 18, 2),
                               LATEST_VERSION),
            ],
            "COLLECTOR_HEADER_DEFAULT_RECOMMENDED"
        ))
