from mcup.cli.ui.elements.collector import Collector, CollectorSection, CollectorInputType, CollectorInput
from mcup.core.utils.version import Version, LATEST_VERSION


class PaperWorldDefaultsCollector(Collector):
    def __init__(self):
        super().__init__()

        self.add_section(CollectorSection(
            "Paper (World Defaults) - Anticheat",
            [
                CollectorInput("anticheat/anti-xray/enabled",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ANTICHEAT_ANTI_XRAY_ENABLED",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("anticheat/anti-xray/engine-mode",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ANTICHEAT_ANTI_XRAY_ENGINE_MODE",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("anticheat/anti-xray/hidden-blocks",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ANTICHEAT_ANTI_XRAY_HIDDEN_BLOCKS",
                               CollectorInputType.STRING_LIST, Version(1, 19), LATEST_VERSION),
                CollectorInput("anticheat/anti-xray/lava-obscures",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ANTICHEAT_ANTI_XRAY_LAVA_OBSCURES",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("anticheat/anti-xray/max-block-height",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ANTICHEAT_ANTI_XRAY_MAX_BLOCK_HEIGHT",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("anticheat/anti-xray/replacement-blocks",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ANTICHEAT_ANTI_XRAY_REPLACEMENT_BLOCKS",
                               CollectorInputType.STRING_LIST, Version(1, 19), LATEST_VERSION),
                CollectorInput("anticheat/anti-xray/update-radius",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ANTICHEAT_ANTI_XRAY_UPDATE_RADIUS",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("anticheat/anti-xray/use-permission",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ANTICHEAT_ANTI_XRAY_USE_PERMISSIONS",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("anticheat/obfuscation/items/hide-durability",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ANTICHEAT_OBFUSCATION_ITEMS_HIDE_DURABILITY",
                               CollectorInputType.BOOL, Version(1, 19), Version(1, 21, 3)),
                CollectorInput("anticheat/obfuscation/items/hide-itemmeta",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ANTICHEAT_OBFUSCATION_ITEMS_HIDE_ITEMMETA",
                               CollectorInputType.BOOL, Version(1, 19), Version(1, 21, 3)),
                CollectorInput("anticheat/obfuscation/items/hide-itemmeta-with-visual-effects",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ANTICHEAT_OBFUSCATION_ITEMS_HIDE_ITEMMETA_WITH_VISUAL_EFFECTS",
                               CollectorInputType.BOOL, Version(1, 19, 2), Version(1, 21, 3))
            ]
        ))
        self.add_section(CollectorSection(
            "Paper (World Defaults) - Chunks",
            [
                CollectorInput("chunks/auto-save-interval", "COLLECTOR_PAPER_WORLD_DEFAULTS_CHUNKS_AUTO_SAVE_INTERVAL",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("chunks/delay-chunk-unloads-by",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_CHUNKS_DELAY_CHUNK_UNLOADS_BY",
                               CollectorInputType.STRING, Version(1, 19), LATEST_VERSION),
                CollectorInput("chunks/entity-per-chunk-save-limit/arrow",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_CHUNKS_ENTITY_PER_CHUNK_SAVE_LIMIT_ARROW",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("chunks/entity-per-chunk-save-limit/ender_pearl",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_CHUNKS_ENTITY_PER_CHUNK_SAVE_LIMIT_ENDER_PEARL",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("chunks/entity-per-chunk-save-limit/experience_orb",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_CHUNKS_ENTITY_PER_CHUNK_SAVE_LIMIT_EXPERIENCE_ORB",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("chunks/entity-per-chunk-save-limit/fireball",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_CHUNKS_ENTITY_PER_CHUNK_SAVE_LIMIT_FIREBALL",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("chunks/entity-per-chunk-save-limit/small_fireball",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_CHUNKS_ENTITY_PER_CHUNK_SAVE_LIMIT_SMALL_FIREBALL",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("chunks/entity-per-chunk-save-limit/snowball",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_CHUNKS_ENTITY_PER_CHUNK_SAVE_LIMIT_SNOWBALL",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("chunks/fixed-chunk-inhabited-time",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_CHUNKS_FIXED_CHUNK_INHABITED_TIME",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("chunks/flush-regions-on-save",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_CHUNKS_FLUSH_REGIONS_ON_SAVE",
                               CollectorInputType.BOOL, Version(1, 19, 4), LATEST_VERSION),
                CollectorInput("chunks/max-auto-save-chunks-per-tick",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_CHUNKS_MAX_AUTO_SAVE_CHUNKS_PER_TICK",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("chunks/prevent-moving-into-unloaded-chunks",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_CHUNKS_PREVENT_MOVING_INTO_UNLOADED_CHUNKS",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION)
            ]
        ))
        self.add_section(CollectorSection(
            "Paper (World Defaults) - Collisions",
            [
                CollectorInput("collisions/allow-player-cramming-damage",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_COLLISIONS_ALLOW_PLAYER_CRAMMING_DAMAGE",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("collisions/allow-vehicle-collisions",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_COLLISIONS_ALLOW_VEHICLE_COLLISIONS",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("collisions/fix-climbing-bypassing-cramming-rule",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_COLLISIONS_FIX_CLIMBING_BYPASSING_CRAMMING_RULE",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("collisions/max-entity-collisions",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_COLLISIONS_MAX_ENTITY_COLLISIONS",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("collisions/only-players-collide",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_COLLISIONS_ONLY_PLAYERS_COLLIDE",
                               CollectorInputType.BOOL,Version(1, 19), LATEST_VERSION)
            ]
        ))
        self.add_section(CollectorSection(
            "Paper (World Defaults) - Command Blocks",
            [
                CollectorInput("command-blocks/force-follow-perm-level",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_COMMAND_BLOCKS_FORCE_FOLLOW_PERM_LEVEL",
                               CollectorInputType.BOOL, Version(1, 20, 4), LATEST_VERSION),
                CollectorInput("command-blocks/permissions-level",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_COMMAND_BLOCKS_PERMISSION_LEVEL",
                               CollectorInputType.INT, Version(1, 20, 4), LATEST_VERSION)
            ]
        ))
        self.add_section(CollectorSection(
            "Paper (World Defaults) - Behavior (Entities)",
            [
                CollectorInput("entities/behavior/allow-spider-world-border-climbing",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_BEHAVIOR_ALLOW_SPIDER_WORLD_BORDER_CLIMBING",
                               CollectorInputType.BOOL, Version(1, 19, 3), LATEST_VERSION),
                CollectorInput("entities/behavior/baby-zombie-movement-modifier",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_BEHAVIOR_BABY_ZOMBIE_MOVEMENT_MODIFIER",
                               CollectorInputType.FLOAT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/cooldown-failed-beehive-releases",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_BEHAVIOR_COOLDOWN_FAILED_BEEHIVE_RELEASES",
                               CollectorInputType.BOOL, Version(1, 21, 4), LATEST_VERSION),
                CollectorInput("entities/behavior/disable-chest-cat-detection",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_BEHAVIOR_DISABLE_CHEST_CAT_DETECTION",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/disable-creeper-lingering-effect",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_BEHAVIOR_DISABLE_CREEPER_LINGERING_EFFECT",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/disable-player-crits",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_BEHAVIOR_DISABLE_PLAYER_CRITS",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/door-breaking-difficulty/husk",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_BEHAVIOR_DOOR_BREAKING_DIFFICULTY_HUSK",
                               CollectorInputType.STRING_LIST, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/door-breaking-difficulty/vindicator",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_BEHAVIOR_DOOR_BREAKING_DIFFICULTY_VINDICATOR",
                               CollectorInputType.STRING_LIST, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/door-breaking-difficulty/zombie",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_BEHAVIOR_DOOR_BREAKING_DIFFICULTY_ZOMBIE",
                               CollectorInputType.STRING_LIST, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/door-breaking-difficulty/zombie_villager",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_BEHAVIOR_DOOR_BREAKING_DIFFICULTY_ZOMBIE_VILLAGER",
                               CollectorInputType.STRING_LIST, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/door-breaking-difficulty/zombified_piglin",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_BEHAVIOR_DOOR_BREAKING_DIFFICULTY_ZOMBIFIED_PIGLIN",
                               CollectorInputType.STRING_LIST, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/ender-dragons-death-always-places-dragon-egg",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_BEHAVIOR_ENDER_DRAGON_DEATH_ALWAYS_PLACES_DRAGON_EGG",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/experience-merge-max-value",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_BEHAVIOR_EXPERIENCE_MERGE_MAX_VALUE",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/mobs-can-always-pick-up-loot/skeletons",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_BEHAVIOR_MOBS_CAN_ALWAYS_PICK_UP_LOOT_SKELETONS",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/mobs-can-always-pick-up-loot/zombies",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_BEHAVIOR_MOBS_CAN_ALWAYS_PICK_UP_LOOT_ZOMBIES",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/nerf-pigmen-from-nether-portals",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_BEHAVIOR_NERF_PIGMEN_FROM_NETHER_PORTALS",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/only-merge-items-horizontally",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_BEHAVIOR_ONLY_MERGE_ITEMS_HORIZONTALLY",
                               CollectorInputType.BOOL, Version(1, 21, 1), LATEST_VERSION),
                CollectorInput("entities/behavior/parrots-are-unaffected-by-player-movement",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_BEHAVIOR_PARROTS_ARE_UNAFFECTED_BY_PLAYER_MOVEMENT",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/phantoms-do-not-spawn-on-creative-players",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_BEHAVIOR_PHANTOMS_DO_NOT_SPAWN_ON_CREATIVE_PLAYERS",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/phantoms-only-attack-insomniacs",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_BEHAVIOR_PHANTOMS_ONLY_ATTACK_INSOMNIACS",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/phantoms-spawn-attempt-max-seconds",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_BEHAVIOR_PHANTOMS_SPAWN_ATTEMPT_MAX_SECONDS",
                               CollectorInputType.INT, Version(1, 19, 2), LATEST_VERSION),
                CollectorInput("entities/behavior/phantoms-spawn-attempt-min-seconds",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_BEHAVIOR_PHANTOMS_SPAWN_ATTEMPT_MIN_SECONDS",
                               CollectorInputType.INT, Version(1, 19, 2), LATEST_VERSION),
                CollectorInput("entities/behavior/piglins-guard-chests",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_BEHAVIOR_PIGLINS_GUARD_CHESTS",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/pillager-patrols/disable",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_BEHAVIOR_PILLAGER_PATROLS_DISABLE",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/pillager-patrols/spawn-chance",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_BEHAVIOR_PILLAGER_PATROLS_SPAWN_CHANCE",
                               CollectorInputType.FLOAT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/pillager-patrols/spawn-delay/per-player",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_BEHAVIOR_PILLAGER_PATROLS_SPAWN_DELAY_PER_PLAYER",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/pillager-patrols/spawn-delay/ticks",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_BEHAVIOR_PILLAGER_PATROLS_SPAWN_DELAY_TICKS",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/pillager-patrols/start/day",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_BEHAVIOR_PILLAGER_PATROLS_START_DAY",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/pillager-patrols/start/per-player",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_BEHAVIOR_PILLAGER_PATROLS_START_PER_PLAYER",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/player-insomnia-start-ticks",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_BEHAVIOR_PLAYER_INSOMNIA_START_TICKS",
                               CollectorInputType.INT, Version(1, 19, 2), LATEST_VERSION),
                CollectorInput("entities/behavior/should-remove-dragon",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_BEHAVIOR_SHOULD_REMOVE_DRAGON",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/spawner-nerfed-mobs-should-jump",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_BEHAVIOR_SPAWNER_NERFED_MOBS_SHOULD_JUMP",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/zombie-villager-infection-chance",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_BEHAVIOR_ZOMBIE_VILLAGER_INFECTION_CHANCE",
                               CollectorInputType.FLOAT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/zombies-target-turtle-eggs", "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_BEHAVIOR_ZOMBIES_TARGET_TURTLE_EGGS",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION)
            ]
        ))
        self.add_section(CollectorSection(
            "Paper (World Defaults) - Armor Stands, Targeting, Markers, Mob Effects, Sniffers and Tracking Ranges "
            "(Entities)",
            [
                CollectorInput("entities/armor-stands/do-collision-entity-lookups",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_ARMOR_STANDS_DO_COLLISION_ENTITY_LOOKUPS",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/armor-stands/tick",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_ARMOR_STANDS_TICK",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/entities-target-with-follow-range",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_ENTITIES_TARGET_WITH_FOLLOW_RANGE",
                               CollectorInputType.BOOL, Version(1, 19), Version(1, 21, 2)),
                CollectorInput("entities/markers/tick", "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_MARKERS_TICK",
                               CollectorInputType.BOOL, Version(1, 19, 4), LATEST_VERSION),
                CollectorInput("entities/mob-effects/immune-to-wither-effect/wither",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_MOB_EFFECTS_IMMUNE_TO_WITHER_EFFECT_WITHER",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/mob-effects/immune-to-wither-effect/wither-skeleton",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_MOB_EFFECTS_IMMUNE_TO_WITHER_EFFECT_WITHER_SKELETON",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/mob-effects/spiders-immune-to-poison-effect",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_MOB_EFFECTS_SPIDERS_IMMUNE_TO_POISON_EFFECT",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/mob-effects/undead-immune-to-certain-effects",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_MOB_EFFECTS_UNDEAD_IMMUNE_TO_CERTAIN_EFFECTS",
                               CollectorInputType.BOOL, Version(1, 19), Version(1, 20, 4)),
                CollectorInput("entities/sniffer/boosted-hatch-time",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SNIFFER_BOOSTED_HATCH_TIME",
                               CollectorInputType.INT, Version(1, 20, 1), LATEST_VERSION),
                CollectorInput("entities/sniffer/hatch-time",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SNIFFER_HATCH_TIME",
                               CollectorInputType.INT, Version(1, 20, 1), LATEST_VERSION),
                CollectorInput("entities/tracking-range-y/enabled",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_TRACKING_RANGE_Y_ENABLED",
                               CollectorInputType.BOOL, Version(1, 20, 1), LATEST_VERSION),
                CollectorInput("entities/tracking-range-y/animal",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_TRACKING_RANGE_Y_ANIMAL",
                               CollectorInputType.INT, Version(1, 20, 1), LATEST_VERSION),
                CollectorInput("entities/tracking-range-y/display",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_TRACKING_RANGE_Y_DISPLAY",
                               CollectorInputType.INT, Version(1, 20, 1), LATEST_VERSION),
                CollectorInput("entities/tracking-range-y/misc",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_TRACKING_RANGE_Y_MISC",
                               CollectorInputType.INT, Version(1, 20, 1), LATEST_VERSION),
                CollectorInput("entities/tracking-range-y/monster",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_TRACKING_RANGE_Y_MONSTER",
                               CollectorInputType.INT, Version(1, 20, 1), LATEST_VERSION),
                CollectorInput("entities/tracking-range-y/other",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_TRACKING_RANGE_Y_OTHER",
                               CollectorInputType.INT, Version(1, 20, 1), LATEST_VERSION),
                CollectorInput("entities/tracking-range-y/player",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_TRACKING_RANGE_Y_PLAYER",
                               CollectorInputType.INT, Version(1, 20, 1), LATEST_VERSION),
            ]
        ))
        self.add_section(CollectorSection(
            "Paper (World Defaults) - Spawning (Entities)",
            [
                CollectorInput("entities/spawning/all-chunks-are-slime-chunks",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_ALL_CHUNKS_ARE_SLIME_CHUNK",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/alt-item-despawn-rate/enabled",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_ALT_ITEM_DESPAWN_RATE_ENABLED",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/alt-item-despawn-rate/items/cobblestone",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_ALT_ITEM_DESPAWN_RATE_ITEMS_COBBLESTONE",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/count-all-mobs-for-spawning",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_COUNT_ALL_MOBS_FOR_SPAWNING",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/creative-arrow-despawn-rate",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_CREATIVE_ARROW_DESPAWN_RATE",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-range-shape",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_DESPAWN_RANGE_SHAPE",
                               CollectorInputType.STRING, Version(1, 21, 1), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/ambient/hard",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_DESPAWN_RANGES_AMBIENT_HARD",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/ambient/soft",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_DESPAWN_RANGES_AMBIENT_SOFT",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/axolotls/hard",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_DESPAWN_RANGES_AXOLOTLS_HARD",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/axolotls/soft",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_DESPAWN_RANGES_AXOLOTLS_SOFT",
                               CollectorInputType.INT,Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/creature/hard",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_DESPAWN_RANGES_CREATURE_HARD",
                               CollectorInputType.INT,  Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/creature/soft",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_DESPAWN_RANGES_CREATURE_SOFT",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/misc/hard",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_DESPAWN_RANGES_MISC_HARD",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/misc/soft",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_DESPAWN_RANGES_MISC_SOFT",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/monster/hard",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_DESPAWN_RANGES_MONSTER_HARD",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/monster/soft",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_DESPAWN_RANGES_MONSTER_SOFT",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/underground_water_creature/hard",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_DESPAWN_RANGES_UNDERGROUND_WATER_CREATURE_HARD",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/underground_water_creature/soft",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_DESPAWN_RANGES_UNDERGROUND_WATER_CREATURE_SOFT",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/water_ambient/hard",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_DESPAWN_RANGES_WATER_AMBIENT_HARD",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/water_ambient/soft",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_DESPAWN_RANGES_WATER_AMBIENT_SOFT",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/water_creature/hard",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_DESPAWN_RANGES_WATER_CREATURE_HARD",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/water_creature/soft",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_DESPAWN_RANGES_WATER_CREATURE_SOFT",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-time/llama_spit",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_DESPAWN_TIME_LLAMA_SPIT",
                               CollectorInputType.INT, Version(1, 21, 3), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-time/snowball",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_DESPAWN_TIME_SNOWBALL",
                               CollectorInputType.INT, Version(1, 21, 3), LATEST_VERSION),
                CollectorInput("entities/spawning/disable-mob-spawner-spawn-egg-transformation",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_DISABLE_MOB_SPAWNER_SPAWN_EGG_TRANSFORMATION",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/duplicate-uuid/mode",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_DUPLICATE_UUID_MODE",
                               CollectorInputType.STRING, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/duplicate-uuid/safe-regen-delete-range",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_DUPLICATE_UUID_SAFE_REGEN_DELETE_RANGE",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/filter-bad-tile-entity-nbt-from-falling-blocks",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_FILTER_BAD_TILE_ENTITY_NBT_FROM_FALLING_BLOCKS",
                               CollectorInputType.BOOL, Version(1, 19, 3), LATEST_VERSION),
                CollectorInput("entities/spawning/filtered-entity-tag-nbt-paths",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_FILTER_ENTITY_TAG_NBT_PATHS",
                               CollectorInputType.STRING_LIST, Version(1, 19, 3), LATEST_VERSION),
                CollectorInput("entities/spawning/filter-nbt-data-from-spawn-eggs-and-related",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_FILTER_NBT_DATA_FROM_SPAWN_EGGS_AND_RELATED",
                               CollectorInputType.BOOL, Version(1, 19), Version(1, 19, 3)),
                CollectorInput("entities/spawning/iron-golems-can-spawn-in-air",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_IRON_GOLEMS_CAN_SPAWN_IN_AIR",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/monster-spawn-max-light-level",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_MONSTER_SPAWN_MAX_LIGHT_LEVEL",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/non-player-arrow-despawn-rate",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_NON_PLAYER_ARROW_DESPAWN_RATE",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/per-player-mob-spawns",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_PER_PLAYER_MOB_SPAWNS",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/scan-for-legacy-ender-dragon",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_SCAN_FOR_LEGACY_ENDER_DRAGON",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/skeleton-horse-thunder-spawn-chance",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_SKELETON_HORSE_THUNDER_SPAWN_CHANCE",
                               CollectorInputType.FLOAT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/slime-spawn-height/slime-chunk/maximum",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_SLIME_SPAWN_HEIGHT_SLIME_CHUNK_MAXIMUM",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/slime-spawn-height/surface-biome/maximum",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_SLIME_SPAWN_HEIGHT_SURFACE_BIOME_MAXIMUM",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/slime-spawn-height/surface-biome/minimum",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_SLIME_SPAWN_HEIGHT_SURFACE_BIOME_MINIMUM",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/spawn-limits/ambient",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_SPAWN_LIMITS_AMBIENT",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/spawn-limits/axolotls",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_SPAWN_LIMITS_AXOLOTLS",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/spawn-limits/creature",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_SPAWN_LIMITS_CREATURE",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/spawn-limits/monster",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_SPAWN_LIMITS_MONSTER",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/spawn-limits/underground_water_creature",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_SPAWN_LIMITS_UNDERGROUND_WATER_CREATURE",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/spawn-limits/water_ambient",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_SPAWN_LIMITS_WATER_AMBIENT",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/spawn-limits/water_creature",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_SPAWN_LIMITS_WATER_CREATURE",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/ticks-per-spawn/ambient",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_TICKS_PER_SPAWN_AMBIENT",
                               CollectorInputType.INT, Version(1, 20, 4), LATEST_VERSION),
                CollectorInput("entities/spawning/ticks-per-spawn/axolotls",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_TICKS_PER_SPAWN_AXOLOTLS",
                               CollectorInputType.INT, Version(1, 20, 4), LATEST_VERSION),
                CollectorInput("entities/spawning/ticks-per-spawn/creature",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_TICKS_PER_SPAWN_CREATURE",
                               CollectorInputType.INT, Version(1, 20, 4), LATEST_VERSION),
                CollectorInput("entities/spawning/ticks-per-spawn/monster",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_TICKS_PER_SPAWN_MONSTER",
                               CollectorInputType.INT, Version(1, 20, 4), LATEST_VERSION),
                CollectorInput("entities/spawning/ticks-per-spawn/underground_water_creature",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_TICKS_PER_SPAWN_UNDERGROUND_WATER_CREATURE",
                               CollectorInputType.INT, Version(1, 20, 4), LATEST_VERSION),
                CollectorInput("entities/spawning/ticks-per-spawn/water_ambient",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_TICKS_PER_SPAWN_WATER_AMBIENT",
                               CollectorInputType.INT, Version(1, 20, 4), LATEST_VERSION),
                CollectorInput("entities/spawning/ticks-per-spawn/water_creature",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_TICKS_PER_SPAWN_WATER_CREATURE",
                               CollectorInputType.INT, Version(1, 20, 4), LATEST_VERSION),
                CollectorInput("entities/spawning/wandering-trader/spawn-chance-failure-increment",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_WANDERING_TRADER_SPAWN_CHANCE_FAILURE_INCREMENT",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/wandering-trader/spawn-chance-max",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_WANDERING_TRADER_SPAWN_CHANCE_MAX",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/wandering-trader/spawn-chance-min",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_WANDERING_TRADER_SPAWN_CHANCE_MIN",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/wandering-trader/spawn-day-length",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_WANDERING_TRADER_SPAWN_DAY_LENGTH",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/wandering-trader/spawn-minute-length",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_WANDERING_TRADER_SPAWN_MINUTE_LENGTH",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/wateranimal-spawn-height/maximum",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_WATERANIMAL_SPAWN_HEIGHT_MAXIMUM",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/wateranimal-spawn-height/minimum",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENTITIES_SPAWNING_WATERANIMAL_SPAWN_HEIGHT_MINIMUM",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
            ]
        ))
        self.add_section(CollectorSection(
            "Paper (World Defaults) - Environment & Feature Seeds",
            [
                CollectorInput("environment/disable-explosion-knockback",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENVIRONMENT_DISABLE_EXPLOSION_KNOCKBACK",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("environment/disable-ice-and-snow",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENVIRONMENT_DISABLE_ICE_AND_SNOW",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("environment/disable-teleportation-suffocation-check",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENVIRONMENT_DISABLE_TELEPORTATION_SUFFOCATION_CHECK",
                               CollectorInputType.BOOL, Version(1, 19), Version(1, 21, 4)),
                CollectorInput("environment/disable-thunder",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENVIRONMENT_DISABLE_THUNDER",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("environment/fire-tick-delay",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENVIRONMENT_FIRE_TICK_DELAY",
                               CollectorInputType.BOOL, Version(1, 19, 2), LATEST_VERSION),
                CollectorInput("environment/frosted-ice/delay/max",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENVIRONMENT_FROSTED_ICE_DELAY_MAX",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("environment/frosted-ice/delay/min",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENVIRONMENT_FROSTED_ICE_DELAY_MIN",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("environment/frosted-ice/enabled",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENVIRONMENT_FROSTED_ICE_ENABLED",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("environment/generate-flat-bedrock",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENVIRONMENT_GENERATE_FLAT_BEDROCK",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("environment/locate-structures-outside-world-border",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENVIRONMENT_LOCATE_STRUCTURES_OUTSIDE_WORLD_BORDER",
                               CollectorInputType.BOOL, Version(1, 20, 4), LATEST_VERSION),
                CollectorInput("environment/max-block-ticks",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENVIRONMENT_MAX_BLOCK_TICKS",
                               CollectorInputType.INT, Version(1, 20, 4), LATEST_VERSION),
                CollectorInput("environment/max-fluid-ticks",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENVIRONMENT_MAX_FLUID_TICKS",
                               CollectorInputType.INT, Version(1, 20, 4), LATEST_VERSION),
                CollectorInput("environment/nether-ceiling-void-damage-height",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENVIRONMENT_NETHER_CEILING_VOID_DAMAGE_HEIGHT",
                               CollectorInputType.STRING, Version(1, 19), LATEST_VERSION),
                CollectorInput("environment/optimize-explosions",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENVIRONMENT_OPTIMIZE_EXPLOSIONS",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("environment/portal-create-radius",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENVIRONMENT_PORTAL_CREATE_RADIUS",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("environment/portal-search-radius",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENVIRONMENT_PORTAL_SEARCH_RADIUS",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("environment/portal-search-vanilla-dimension-scaling",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENVIRONMENT_PORTAL_SEARCH_VANILLA_DIMENSION_SCALING",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("environment/treasure-maps/enabled",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENVIRONMENT_TREASURE_MAPS_ENABLED",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("environment/treasure-maps/find-already-discovered/loot-tables",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENVIRONMENT_TREASURE_MAPS_FIND_ALREADY_DISCOVERED_LOOT_TABLES",
                               CollectorInputType.STRING_LIST, Version(1, 19), LATEST_VERSION),
                CollectorInput("environment/treasure-maps/find-already-discovered/villager-trade",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENVIRONMENT_TREASURE_MAPS_FIND_ALREADY_DISCOVERED_VILLAGER_TRADE",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("environment/void-damage-amount",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENVIRONMENT_VOID_DAMAGE_AMOUNT",
                               CollectorInputType.INT, Version(1, 21, 1), LATEST_VERSION),
                CollectorInput("environment/void-damage-min-build-height-offset",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENVIRONMENT_VOID_DAMAGE_MIN_BUILD_HEIGHT_OFFSET",
                               CollectorInputType.INT, Version(1, 21, 1), LATEST_VERSION),
                CollectorInput("environment/water-over-lava-flow-speed",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENVIRONMENT_WATER_OVER_LAVA_FLOW_SPEED",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("environment/feature-seeds/generate-random-seeds-for-all",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_ENVIRONMENT_FEATURE_SEEDS_GENERATE_RANDOM_SEEDS_FOR_ALL",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
            ]
        ))
        self.add_section(CollectorSection(
            "Paper (World Defaults) - Fishing Time Range, Fixes, Hoppers and Lootables",
            [
                CollectorInput("fishing-time-range/maximum",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_FISHING_TIME_RANGE_MAXIMUM",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("fishing-time-range/minimum",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_FISHING_TIME_RANGE_MINIMUM",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("fixes/disable-unloaded-chunk-enderpearl-exploit",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_FIXES_DISABLE_UNLOADED_CHUNK_ENDERPEARL_EXPLOIT",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("fixes/falling-block-height-nerf",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_FIXES_FALLING_BLOCK_HEIGHT_NERF",
                               CollectorInputType.STRING, Version(1, 19), LATEST_VERSION),
                CollectorInput("fixes/fix-curing-zombie-villager-discount-exploit",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_FIXES_FIX_CURING_VILLAGER_DISCOUNT_EXPLOIT",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("fixes/fix-items-merging-through-walls",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_FIXES_FIX_ITEMS_MERGING_THROUGH_WALLS",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("fixes/prevent-tnt-from-moving-in-water",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_FIXES_PREVENT_TNT_FROM_MOVING_IN_WATER",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("fixes/split-overstacked-loot",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_FIXES_SPLIT_OVERSTACKED_LOOT",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("fixes/tnt-entity-height-nerf",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_FIXES_TNT_ENTITY_HEIGHT_NERF",
                               CollectorInputType.STRING, Version(1, 19), LATEST_VERSION),
                CollectorInput("hoppers/cooldown-when-full",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_HOPPERS_COOLDOWN_WHEN_FULL",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("hoppers/disable-move-event",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_HOPPERS_DISABLE_MOVE_EVENT",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("hoppers/ignore-occluding-blocks",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_HOPPERS_IGNORE_OCCLUDING_BLOCKS",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("lootables/auto-replenish",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_LOOTABLES_AUTO_REPLENISH",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("lootables/max-refills",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_LOOTABLES_MAX_REFILLS",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("lootables/refresh-max",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_LOOTABLES_REFRESH_MAX",
                               CollectorInputType.STRING, Version(1, 19), LATEST_VERSION),
                CollectorInput("lootables/refresh-min",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_LOOTABLES_REFRESH_MIN",
                               CollectorInputType.STRING, Version(1, 19), LATEST_VERSION),
                CollectorInput("lootables/reset-seed-on-fill",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_LOOTABLES_RESET_SEED_ON_FILL",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("lootables/restrict-player-reloot",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_LOOTABLES_RESTRICT_PLAYER_RELOOT",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("lootables/restrict-player-reloot-time",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_LOOTABLES_RESTRICT_PLAYER_RELOOT_TIME",
                               CollectorInputType.STRING, Version(1, 20, 1), LATEST_VERSION),
                CollectorInput("lootables/retain-unlooted-shulker-box-loot-table-on-non-player-break",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_LOOTABLES_RETAIN_UNLOOTED_SHULKER_BOX_LOOT_TABLE_ON_NON_PLAYER_BREAK",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
            ]
        ))
        self.add_section(CollectorSection(
            "Paper (World Defaults) - Maps, Max Growth Height and Misc",
            [
                CollectorInput("maps/item-frame-cursor-limit",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_MAPS_ITEM_FRAME_CURSOR_LIMIT",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("maps/item-frame-cursor-update-interval",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_MAPS_ITEM_FRAME_CURSOR_UPDATE_INTERVAL",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("max-growth-height/bamboo/max",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_MAX_GROWTH_HEIGHT_BAMBOO_MAX",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("max-growth-height/bamboo/min",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_MAX_GROWTH_HEIGHT_BAMBOO_MIN",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("max-growth-height/cactus",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_MAX_GROWTH_HEIGHT_CACTUS",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("max-growth-height/reeds",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_MAX_GROWTH_HEIGHT_REEDS",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("misc/alternate-current-update-order",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_MISC_ALTERNATE_CURRENT_UPDATE_ORDER",
                               CollectorInputType.STRING, Version(1, 21, 1), LATEST_VERSION),
                CollectorInput("misc/disable-end-credits",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_MISC_DISABLE_END_CREDITS",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("misc/disable-relative-projectile-velocity",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_MISC_DISABLE_RELATIVE_PROJECTILE_VELOCITY",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("misc/disable-sprint-interruption-on-attack",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_MISC_DISABLE_SPRINT_INTERRUPTION_ON_ATTACK",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("misc/legacy-ender-pearl-behavior",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_MISC_LEGACY_ENDER_PEARL_BEHAVIOR",
                               CollectorInputType.BOOL, Version(1, 21, 3), LATEST_VERSION),
                CollectorInput("misc/light-queue-size",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_MISC_LIGHT_QUEUE_SIZE",
                               CollectorInputType.INT, Version(1, 19), Version(1, 21, 4)),
                CollectorInput("misc/max-leash-distance",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_MISC_MAX_LEASH_DISTANCE",
                               CollectorInputType.STRING, Version(1, 19), LATEST_VERSION),
                CollectorInput("misc/redstone-implementation",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_MISC_REDSTONE_IMPLEMENTATION",
                               CollectorInputType.STRING, Version(1, 19), LATEST_VERSION),
                CollectorInput("misc/shield-blocking-delay",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_MISC_SHIELD_BLOCKING_DELAY",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("misc/show-sign-click-command-failure-msgs-to-player",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_MISC_SHOW_SIGN_CLICK_COMMAND_FAILURE_MSGS_TO_PLAYER",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("misc/update-pathfinding-on-block-update",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_MISC_UPDATE_PATHFINDING_ON_BLOCK_UPDATE",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
            ]
        ))
        self.add_section(CollectorSection(
            "Paper (World Defaults) - Scoreboards, Spawn and Tick Rates",
            [
                CollectorInput("scoreboards/allow-non-player-entities-on-scoreboards",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_SCOREBOARDS_ALLOW_NON_PLAYER_ENTITIES_ON_SCOREBOARDS",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("scoreboards/use-vanilla-world-scoreboard-name-coloring",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_SCOREBOARDS_USE_VANILLA_WORLD_SCOREBOARD_NAME_COLORING",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("spawn/allow-using-signs-inside-spawn-protection",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_SPAWN_ALLOW_USING_SIGNS_INSIDE_SPAWN_PROTECTION",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("spawn/keep-spawn-loaded",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_SPAWN_KEEP_SPAWN_LOADED",
                               CollectorInputType.BOOL, Version(1, 19), Version(1, 20, 4)),
                CollectorInput("spawn/keep-spawn-loaded-range",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_SPAWN_KEEP_SPAWN_LOADED_RANGE",
                               CollectorInputType.INT, Version(1, 19), Version(1, 20, 4)),
                CollectorInput("tick-rates/behavior/villager/validatenearbypoi",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_TICK_RATES_BEHAVIOR_VILLAGER_VALIDATENEARBYPOI",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("tick-rates/container-update",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_TICK_RATES_CONTAINER_UPDATE",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("tick-rates/dry-farmland",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_TICK_RATES_DRY_FARMLAND",
                               CollectorInputType.INT, Version(1, 20, 2), LATEST_VERSION),
                CollectorInput("tick-rates/wet-farmland",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_TICK_RATES_WET_FARMLAND",
                               CollectorInputType.INT, Version(1, 20, 2), LATEST_VERSION),
                CollectorInput("tick-rates/grass-spread",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_TICK_RATES_GRASS_SPREAD",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("tick-rates/mob-spawner",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_TICK_RATES_MOB_SPAWNER",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
                CollectorInput("tick-rates/sensor/villager/secondarypoisensor",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_TICK_RATES_SENSOR_VILLAGER_SECONDARYPOISENSOR",
                               CollectorInputType.INT, Version(1, 19), LATEST_VERSION),
            ]
        ))
        self.add_section(CollectorSection(
            "Paper (World Defaults) - Unsupported Settings",
            [
                CollectorInput("unsupported-settings/disable-world-ticking-when-empty",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_UNSUPPORTED_SETTINGS_DISABLE_WORLD_TICKING_WHEN_EMPTY",
                               CollectorInputType.BOOL, Version(1, 20, 4), LATEST_VERSION),
                CollectorInput("unsupported-settings/fix-invulnerable-end-crystal-exploit",
                               "COLLECTOR_PAPER_WORLD_DEFAULTS_UNSUPPORTED_SETTINGS_FIX_INVULNERABLE_END_CRYSTAL_EXPLOIT",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION)
            ],
            "COLLECTOR_HEADER_DEFAULT_RECOMMENDED"
        ))
