from mcup.cli.ui.elements.collector import Collector, CollectorSection, CollectorInputType, CollectorInput
from mcup.core.utils.version import Version, LATEST_VERSION


class PaperWorldDefaultsCollector(Collector):
    def __init__(self):
        super().__init__()

        self.add_section(CollectorSection(
            "Paper (World Defaults) - Anticheat",
            [
                CollectorInput("anticheat/anti-xray/enabled", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("anticheat/anti-xray/engine-mode", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("anticheat/anti-xray/hidden-blocks", "", CollectorInputType.STRING_LIST,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("anticheat/anti-xray/lava-obscures", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("anticheat/anti-xray/max-block-height", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("anticheat/anti-xray/replacement-blocks", "", CollectorInputType.STRING_LIST,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("anticheat/anti-xray/update-radius", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("anticheat/anti-xray/use-permission", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("anticheat/obfuscation/items/hide-durability", "", CollectorInputType.BOOL,
                               Version(1, 19), Version(1, 21, 3)),
                CollectorInput("anticheat/obfuscation/items/hide-itemmeta", "", CollectorInputType.BOOL,
                               Version(1, 19), Version(1, 21, 3)),
                CollectorInput("anticheat/obfuscation/items/hide-itemmeta-with-visual-effects", "",
                               CollectorInputType.BOOL, Version(1, 19, 2), Version(1, 21, 3))
            ]
        ))
        self.add_section(CollectorSection(
            "Paper (World Defaults) - Chunks",
            [
                CollectorInput("chunks/auto-save-interval", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("chunks/delay-chunk-unloads-by", "", CollectorInputType.STRING,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("chunks/entity-per-chunk-save-limit/arrow", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("chunks/entity-per-chunk-save-limit/ender_pearl", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("chunks/entity-per-chunk-save-limit/experience_orb", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("chunks/entity-per-chunk-save-limit/fireball", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("chunks/entity-per-chunk-save-limit/small_fireball", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("chunks/entity-per-chunk-save-limit/snowball", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("chunks/fixed-chunk-inhabited-time", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("chunks/flush-regions-on-save", "", CollectorInputType.BOOL,
                               Version(1, 19, 4), LATEST_VERSION),
                CollectorInput("chunks/max-auto-save-chunks-per-tick", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("chunks/prevent-moving-into-unloaded-chunks", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION)
            ]
        ))
        self.add_section(CollectorSection(
            "Paper (World Defaults) - Collisions",
            [
                CollectorInput("collisions/allow-player-cramming-damage", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("collisions/allow-vehicle-collisions", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("collisions/fix-climbing-bypassing-cramming-rule", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("collisions/max-entity-collisions", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("collisions/only-players-collide", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION)
            ]
        ))
        self.add_section(CollectorSection(
            "Paper (World Defaults) - Command Blocks",
            [
                CollectorInput("command-blocks/force-follow-perm-level", "", CollectorInputType.BOOL,
                               Version(1, 20, 4), LATEST_VERSION),
                CollectorInput("command-blocks/permissions-level", "", CollectorInputType.INT,
                               Version(1, 20, 4), LATEST_VERSION)
            ]
        ))
        self.add_section(CollectorSection(
            "Paper (World Defaults) - Behavior (Entities)",
            [
                CollectorInput("entities/behavior/allow-spider-world-border-climbing", "", CollectorInputType.BOOL,
                               Version(1, 19, 3), LATEST_VERSION),
                CollectorInput("entities/behavior/baby-zombie-movement-modifier", "", CollectorInputType.FLOAT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/cooldown-failed-beehive-releases", "", CollectorInputType.BOOL,
                               Version(1, 21, 4), LATEST_VERSION),
                CollectorInput("entities/behavior/disable-chest-cat-detection", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/disable-creeper-lingering-effect", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/disable-player-crits", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/door-breaking-difficulty/husk", "", CollectorInputType.STRING_LIST,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/door-breaking-difficulty/vindicator", "",
                               CollectorInputType.STRING_LIST, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/door-breaking-difficulty/zombie", "", CollectorInputType.STRING_LIST,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/door-breaking-difficulty/zombie_villager", "",
                               CollectorInputType.STRING_LIST, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/door-breaking-difficulty/zombified_piglin", "",
                               CollectorInputType.STRING_LIST, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/ender-dragons-death-always-places-dragon-egg", "",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/experience-merge-max-value", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/mobs-can-always-pick-up-loot/skeletons", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/mobs-can-always-pick-up-loot/zombies", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/nerf-pigmen-from-nether-portals", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/only-merge-items-horizontally", "", CollectorInputType.BOOL,
                               Version(1, 21, 1), LATEST_VERSION),
                CollectorInput("entities/behavior/parrots-are-unaffected-by-player-movement", "",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/phantoms-do-not-spawn-on-creative-players", "",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/phantoms-only-attack-insomniacs", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/phantoms-spawn-attempt-max-seconds", "", CollectorInputType.INT,
                               Version(1, 19, 2), LATEST_VERSION),
                CollectorInput("entities/behavior/phantoms-spawn-attempt-min-seconds", "", CollectorInputType.INT,
                               Version(1, 19, 2), LATEST_VERSION),
                CollectorInput("entities/behavior/piglins-guard-chests", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/pillager-patrols/disable", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/pillager-patrols/spawn-chance", "",
                               CollectorInputType.FLOAT, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/pillager-patrols/spawn-delay/per-player", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/pillager-patrols/spawn-delay/ticks", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/pillager-patrols/start/day", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/pillager-patrols/start/per-player", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/player-insomnia-start-ticks", "", CollectorInputType.INT,
                               Version(1, 19, 2), LATEST_VERSION),
                CollectorInput("entities/behavior/should-remove-dragon", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/spawner-nerfed-mobs-should-jump", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/zombie-villager-infection-chance", "", CollectorInputType.FLOAT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/behavior/zombies-target-turtle-eggs", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION)
            ]
        ))
        self.add_section(CollectorSection(
            "Paper (World Defaults) - Armor Stands, Targeting, Markers, Mob Effects and Sniffers (Entities)",
            [
                CollectorInput("entities/armor-stands/do-collision-entity-lookups", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/armor-stands/tick", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/entities-target-with-follow-range", "", CollectorInputType.BOOL,
                               Version(1, 19), Version(1, 21, 2)),
                CollectorInput("entities/markers/tick", "", CollectorInputType.BOOL,
                               Version(1, 19, 4), LATEST_VERSION),
                CollectorInput("entities/mob-effects/immune-to-wither-effect/wither", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/mob-effects/immune-to-wither-effect/wither-skeleton", "",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/mob-effects/spiders-immune-to-poison-effect", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/mob-effects/undead-immune-to-certain-effects", "", CollectorInputType.BOOL,
                               Version(1, 19), Version(1, 20, 4)),
                CollectorInput("entities/sniffer/boosted-hatch-time", "", CollectorInputType.INT,
                               Version(1, 20, 1), LATEST_VERSION),
                CollectorInput("entities/sniffer/hatch-time", "", CollectorInputType.INT,
                               Version(1, 20, 1), LATEST_VERSION),
            ]
        ))
        self.add_section(CollectorSection(
            "Paper (World Defaults) - Spawning (Entities)",
            [
                CollectorInput("entities/spawning/all-chunks-are-slime-chunks", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/alt-item-despawn-rate/enabled", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/alt-item-despawn-rate/items/cobblestone", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/count-all-mobs-for-spawning", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/creative-arrow-despawn-rate", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-range-shape", "", CollectorInputType.STRING,
                               Version(1, 21, 1), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/ambient/hard", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/ambient/soft", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/axolotls/hard", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/axolotls/soft", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/creature/hard", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/creature/soft", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/misc/hard", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/misc/soft", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/monster/hard", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/monster/soft", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/underground_water_creature/hard", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/underground_water_creature/soft", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/water_ambient/hard", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/water_ambient/soft", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/water_creature/hard", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-ranges/water_creature/soft", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-time/llama_spit", "", CollectorInputType.INT,
                               Version(1, 21, 3), LATEST_VERSION),
                CollectorInput("entities/spawning/despawn-time/snowball", "", CollectorInputType.INT,
                               Version(1, 21, 3), LATEST_VERSION),
                CollectorInput("entities/spawning/disable-mob-spawner-spawn-egg-transformation", "",
                               CollectorInputType.BOOL, Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/duplicate-uuid/mode", "", CollectorInputType.STRING,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/duplicate-uuid/safe-regen-delete-range", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/filter-bad-tile-entity-nbt-from-falling-blocks", "",
                               CollectorInputType.BOOL, Version(1, 19, 3), LATEST_VERSION),
                CollectorInput("entities/spawning/filtered-entity-tag-nbt-paths", "", CollectorInputType.STRING_LIST,
                               Version(1, 19, 3), LATEST_VERSION),
                CollectorInput("entities/spawning/filter-nbt-data-from-spawn-eggs-and-related", "",
                               CollectorInputType.BOOL, Version(1, 19), Version(1, 19, 3)),
                CollectorInput("entities/spawning/iron-golems-can-spawn-in-air", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/monster-spawn-max-light-level", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/non-player-arrow-despawn-rate", "", CollectorInputType.INT,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/per-player-mob-spawns", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
                CollectorInput("entities/spawning/scan-for-legacy-ender-dragon", "", CollectorInputType.BOOL,
                               Version(1, 19), LATEST_VERSION),
            ]
        ))
