from mcup.cli.ui.elements.collector import Collector, CollectorSection, CollectorInput, CollectorInputType
from mcup.core.utils.version import Version, LATEST_VERSION


class PaperCollector(Collector):
    def __init__(self):
        super().__init__()

        self.add_section(CollectorSection(
            "Paper - General Settings",
            [
                CollectorInput("effect-modifiers/strength", "Strength effect modifier", CollectorInputType.FLOAT,
                               Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("effect-modifiers/weakness", "Weakness effect modifier", CollectorInputType.FLOAT,
                               Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("stackable-buckets/lava", "Allow lava buckets stacking", CollectorInputType.BOOL,
                               Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("stackable-buckets/water", "Allow water buckets stacking", CollectorInputType.BOOL,
                               Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("stackable-buckets/milk", "Allow milk buckets stacking", CollectorInputType.BOOL,
                               Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("settings/baby-zombie-movement-speed", "Baby zombie movement speed",
                               CollectorInputType.FLOAT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("settings/limit-player-interactions", "Limit player interactions",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("warnWhenSettingExcessiveVelocity", "Warn when setting excessive velocity",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("data-value-allowed-items", "Data value allowed items", CollectorInputType.STRING,
                               Version(1, 8, 8), LATEST_VERSION),
            ]
        ))
        self.add_section(CollectorSection(
            "Paper - World Settings",
            [
                CollectorInput("world-settings/default/verbose", "Show detailed report in console",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/use-hopper-check", "Use hopper check", CollectorInputType.BOOL,
                               Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/disable-mood-sounds", "Disable mood sounds",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/fix-cannons", "Fix cannons", CollectorInputType.BOOL,
                               Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/optimize-explosions", "Optimize explosions",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/mob-spawner-tick-rate", "Mob spawner tick rate", CollectorInputType.INT,
                               Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/cache-chunk-maps", "Cache chunk maps", CollectorInputType.BOOL,
                               Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/squid-spawn-height/minimum", "Minimal squid spawn height",
                               CollectorInputType.FLOAT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/squid-spawn-width/maximum", "Maximal squid spawn width",
                               CollectorInputType.FLOAT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/tnt-explosion-volume", "TNT explosion volume",
                               CollectorInputType.FLOAT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/max-growth-height/cactus", "Max cactus growth height",
                               CollectorInputType.INT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/max-growth-height/reeds", "Max reeds growth height",
                               CollectorInputType.INT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/fishing-time-range/MinimumTicks",
                               "Minimal fishing time in ticks",
                               CollectorInputType.INT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/fishing-time-range/MaximumTicks",
                               "Maximal fishing time in ticks",
                               CollectorInputType.INT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/player-exhaustion/block-break",
                               "Player exhaustion during block break",
                               CollectorInputType.FLOAT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/player-exhaustion/swimming",
                               "Player exhaustion during swimming",
                               CollectorInputType.FLOAT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/despawn-ranges/soft", "Soft despawn range",
                               CollectorInputType.INT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/despawn-ranges/hard", "Hard despawn range",
                               CollectorInputType.INT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/remove-unloaded/enderpearls", "Remove unloaded enderpearls",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/remove-unloaded/tnt-entities", "Remove unloaded TNT entities",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/remove-unloaded/falling-blocks", "Remove unloaded falling blocks",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/game-mechanics/boats-drop-boats", "Boat drop boats",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/game-mechanics/disable-player-crits", "Disable player crits",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/game-mechanics/disable-chest-cat-detection",
                               "Disable chest cat detection", CollectorInputType.BOOL,
                               Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/game-mechanics/disable-end-credits", "Disable end credits",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/load-chunks/enderpearls", "Enderpearls load chunks",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/load-chunks/tnt-entities", "TNT entities load chunks",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/load-chunks/falling-blocks", "Falling blocks load chunks",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/fast-drain/lava", "Lava fast drain", CollectorInputType.BOOL,
                               Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/fast-drain/water", "Water fast drain", CollectorInputType.BOOL,
                               Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/lava-flow-speed/normal", "Normal lava flow speed",
                               CollectorInputType.INT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/lava-flow-speed/nether", "Nether lava flow speed",
                               CollectorInputType.INT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/use-async-lighting", "Use async lighting",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/portal-search-radius", "Portal search radius",
                               CollectorInputType.INT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/disable-thunder", "Disable thunder",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/disable-ice-and-snow", "Disable ice and snow",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/tick-next-tick-list-cap", "Max scheduled block updates per tick",
                               CollectorInputType.INT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/tick-next-tick-list-cap-ignores-redstone",
                               "Max scheduled block updates ignore redstone",
                               CollectorInputType.INT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/keep-spawn-loaded", "Keep spawn loaded",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/generator-settings/canyon", "Generate canyons",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/generator-settings/caves", "Generate caves",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/generator-settings/dungeon", "Generate dungeons",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/generator-settings/fortress", "Generate fortresses",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/generator-settings/mineshaft", "Generate mineshafts",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/generator-settings/monument", "Generate monuments",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/generator-settings/stronghold", "Generate strongholds",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/generator-settings/temple", "Generate temples",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/generator-settings/village", "Generate villages",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/generator-settings/flat-bedrock", "Generate flat bedrocks",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/remove-invalid-mob-spawner-tile-entities",
                               "Remove invalid mob spawner tiles", CollectorInputType.BOOL,
                               Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/player-blocking-damage-multiplier",
                               "Player block damage multiplier", CollectorInputType.FLOAT,
                               Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/falling-block-height-nerf", "Falling block height nerf",
                               CollectorInputType.INT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/nether-ceiling-void-damage", "Deal damage above nether ceiling",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/all-chunks-are-slime-chunks", "All chunks are slime chunks",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/allow-undead-horse-leashing", "Allow undead horse leashing",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/container-update-tick-rate", "Container update tick rate",
                               CollectorInputType.INT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/falling-blocks-collide-with-signs",
                               "Falling block collide with signs", CollectorInputType.BOOL,
                               Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/allow-block-location-tab-completion",
                               "Allow block location tab completion", CollectorInputType.BOOL,
                               Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/disable-explosion-knockback", "Disable explosion knockback",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/tnt-entity-height-nerf", "TNT entity height nerf",
                               CollectorInputType.INT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/water-over-lava-flow-speed", "Water over lava flow speed",
                               CollectorInputType.INT, Version(1, 8, 8), LATEST_VERSION),
                CollectorInput("world-settings/default/disable-teleportation-suffocation-check",
                               "Disable teleportation suffocation check",
                               CollectorInputType.BOOL, Version(1, 8, 8), LATEST_VERSION),
            ],
            "Warning: It's recommended to leave all these settings as default"
        ))
