from mcup.cli.ui.elements.collector import Collector, CollectorSection, CollectorInput, CollectorInputType
from mcup.core.utils.version import Version, LATEST_VERSION


class SpigotCollector(Collector):
    def __init__(self):
        super().__init__()

        self.add_section(CollectorSection(
            "Spigot - General Settings",
            [
                CollectorInput("settings/debug", "COLLECTOR_SPIGOT_SETTINGS_DEBUG", CollectorInputType.BOOL,
                               Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("settings/save-user-cache-on-stop-only",
                               "COLLECTOR_SPIGOT_SETTINGS_SAVE_USER_CACHE_ON_STOP",
                               CollectorInputType.BOOL, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("settings/filter-creative-items", "COLLECTOR_SPIGOT_SETTINGS_FILTER_CREATIVE_ITEMS",
                               CollectorInputType.BOOL,
                               Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("settings/moved-wrongly-threshold", "COLLECTOR_SPIGOT_SETTINGS_MOVED_WRONGLY_THRESHOLD",
                               CollectorInputType.FLOAT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("settings/moved-too-quickly-threshold",
                               "COLLECTOR_SPIGOT_SETTINGS_MOVED_TOO_QUICKLY_THRESHOLD",
                               CollectorInputType.FLOAT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("settings/bungeecord", "COLLECTOR_SPIGOT_SETTINGS_BUNGEECORD", CollectorInputType.BOOL,
                               Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("settings/late-bind", "COLLECTOR_SPIGOT_SETTINGS_LATE_BIND",
                               CollectorInputType.BOOL, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("settings/sample-count", "COLLECTOR_SPIGOT_SETTINGS_SAMPLE_COUNT",
                               CollectorInputType.INT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("settings/player-shuffle", "COLLECTOR_SPIGOT_SETTINGS_PLAYER_SHUFFLE",
                               CollectorInputType.INT,
                               Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("settings/user-cache-size", "COLLECTOR_SPIGOT_SETTINGS_USER_CACHE_SIZE",
                               CollectorInputType.INT,
                               Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("settings/int-cache-limit", "COLLECTOR_SPIGOT_SETTINGS_INT_CACHE_LIMIT",
                               CollectorInputType.INT,
                               Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("settings/timeout-time", "COLLECTOR_SPIGOT_SETTINGS_TIMEOUT_TIME",
                               CollectorInputType.INT,
                               Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("settings/restart-on-crash", "COLLECTOR_SPIGOT_SETTINGS_RESTART_ON_CRASH",
                               CollectorInputType.BOOL, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("settings/restart-script", "COLLECTOR_SPIGOT_SETTINGS_RESTART_SCRIPT",
                               CollectorInputType.STRING, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("settings/netty-threads", "COLLECTOR_SPIGOT_SETTINGS_NETTY_THREADS",
                               CollectorInputType.INT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("settings/attribute/maxHealth", "COLLECTOR_SPIGOT_SETTINGS_ATTRIBUTE_MAX_HEALTH",
                               CollectorInputType.FLOAT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("settings/attribute/movementSpeed", "COLLECTOR_SPIGOT_SETTINGS_ATTRIBUTE_MOVEMENT_SPEED",
                               CollectorInputType.FLOAT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("settings/attribute/attackDamage", "COLLECTOR_SPIGOT_SETTINGS_ATTRIBUTE_ATTACK_DAMAGE",
                               CollectorInputType.FLOAT, Version(1, 8, 0), LATEST_VERSION),
            ]
        ))
        self.add_section(CollectorSection(
            "Spigot - Commands",
            [
                CollectorInput("commands/silent-commandblock-console",
                               "COLLECTOR_SPIGOT_COMMANDS_SILENT_COMMANDBLOCK_CONSOLE",
                               CollectorInputType.BOOL, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("commands/log", "COLLECTOR_SPIGOT_COMMANDS_LOG", CollectorInputType.BOOL,
                               Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("commands/spam-exclusions", "COLLECTOR_SPIGOT_COMMANDS_SPAM_EXCLUSIONS",
                               CollectorInputType.STRING_LIST, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("commands/replace-commands", "COLLECTOR_SPIGOT_COMMANDS_REPLACE_COMMANDS",
                               CollectorInputType.STRING_LIST, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("commands/tab-complete", "COLLECTOR_SPIGOT_COMMANDS_TAB_COMPLETE",
                               CollectorInputType.INT, Version(1, 8, 0), LATEST_VERSION),
            ]
        ))
        self.add_section(CollectorSection(
            "Spigot - Messages",
            [
                CollectorInput("messages/restart", "COLLECTOR_SPIGOT_MESSAGES_RESTART", CollectorInputType.STRING,
                               Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("messages/whitelist", "COLLECTOR_SPIGOT_MESSAGES_WHITELIST", CollectorInputType.STRING,
                               Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("messages/unknown-command", "COLLECTOR_SPIGOT_MESSAGES_UNKNOWN_COMMAND",
                               CollectorInputType.STRING, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("messages/server-full", "COLLECTOR_SPIGOT_MESSAGES_SERVER_FULL",
                               CollectorInputType.STRING, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("messages/outdated-client", "COLLECTOR_SPIGOT_MESSAGES_OUTDATED_CLIENT",
                               CollectorInputType.STRING, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("messages/outdated-server", "COLLECTOR_SPIGOT_MESSAGES_OUTDATED_SERVER",
                               CollectorInputType.STRING, Version(1, 8, 0), LATEST_VERSION),
            ]
        ))
        self.add_section(CollectorSection(
            "Spigot - Statistics",
            [
                CollectorInput("stats/disable-saving", "COLLECTOR_SPIGOT_STATS_DISABLE_SAVING",
                               CollectorInputType.STRING, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("stats/forced-stats", "COLLECTOR_SPIGOT_STATS_FORCED_STATS",
                               CollectorInputType.STRING_LIST, Version(1, 8, 0), LATEST_VERSION),
            ]
        ))
        self.add_section(CollectorSection(
            "Spigot - World Settings",
            [
                CollectorInput("world-settings/default/verbose", "COLLECTOR_SPIGOT_WORLD_SETTINGS_VERBOSE",
                               CollectorInputType.BOOL, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/enable-zombie-pigmen-portal-spawns",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_ENABLE_ZOMBIE_PIGMEN_PORTAL_SPAWNS",
                               CollectorInputType.BOOL, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/wither-spawn-sound-radius",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_WITHER_SPAWN_SOUND_RADIUS",
                               CollectorInputType.INT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/zombie-aggressive-towards-villager",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_ZOMBIE_AGGRESSIVE_TOWARDS_VILLAGER",
                               CollectorInputType.BOOL, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/hanging-tick-frequency",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_HANGING_TICK_FREQUENCY", CollectorInputType.INT,
                               Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/dragon-death-sound-radius",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_DRAGON_DEATH_SOUND_RADIUS",
                               CollectorInputType.INT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/mob-spawn-range",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_MOB_SPAWN_RANGE",
                               CollectorInputType.INT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/anti-xray/enabled",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_ANTI_XRAY_ENABLED",
                               CollectorInputType.BOOL, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/anti-xray/engine-mode",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_ANTI_XRAY_ENGINE_MODE",
                               CollectorInputType.INT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/anti-xray/hide-blocks",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_ANTI_XRAY_HIDE_BLOCKS",
                               CollectorInputType.INT_LIST, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/anti-xray/replace-blocks",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_ANTI_XRAY_REPLACE_BLOCKS", CollectorInputType.INT_LIST,
                               Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/nerf-spawner-mobs",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_NERF_SPAWNER_MOBS",
                               CollectorInputType.BOOL, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/growth/cactus-modifier",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_GROWTH_CACTUS_MODIFIER",
                               CollectorInputType.INT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/growth/cane-modifier",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_GROWTH_CANE_MODIFIER",
                               CollectorInputType.INT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/growth/melon-modifier",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_GROWTH_MELON_MODIFIER",
                               CollectorInputType.INT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/growth/mushroom-modifier",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_GROWTH_MUSHROOM_MODIFIER",
                               CollectorInputType.INT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/growth/pumpkin-modifier",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_GROWTH_PUMPKIN_MODIFIER",
                               CollectorInputType.INT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/growth/sapling-modifier",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_GROWTH_SAPLING_MODIFIER",
                               CollectorInputType.INT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/growth/wheat-modifier",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_GROWTH_WHEAT_MODIFIER",
                               CollectorInputType.INT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/entity-activation-range/animals",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_ENTITY_ACTIVATION_RANGE_ANIMALS",
                               CollectorInputType.INT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/entity-activation-range/monsters",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_ENTITY_ACTIVATION_RANGE_MONSTERS",
                               CollectorInputType.INT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/entity-activation-range/misc",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_ENTITY_ACTIVATION_RANGE_MISC",
                               CollectorInputType.INT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/entity-tracking-range/players",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_ENTITY_TRACKING_RANGE_PLAYERS",
                               CollectorInputType.INT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/entity-tracking-range/animals",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_ENTITY_TRACKING_RANGE_ANIMALS",
                               CollectorInputType.INT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/entity-tracking-range/monsters",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_ENTITY_TRACKING_RANGE_MONSTERS",
                               CollectorInputType.INT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/entity-tracking-range/misc",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_ENTITY_TRACKING_RANGE_MISC",
                               CollectorInputType.INT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/entity-tracking-range/other",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_ENTITY_TRACKING_RANGE_OTHER",
                               CollectorInputType.INT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/hopper-alt-ticking",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_HOPPER_ALT_TICKING",
                               CollectorInputType.BOOL, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/ticks-per/hopper-transfer",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_TICKS_PER_HOPPER_TRANSFER",
                               CollectorInputType.INT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/ticks-per/hopper-check",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_TICKS_PER_HOPPER_CHECK",
                               CollectorInputType.INT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/hopper-amount",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_HOPPER_AMOUNT", CollectorInputType.INT,
                               Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/random-light-updates",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_RANDOM_LIGHT_UPDATES",
                               CollectorInputType.BOOL, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/save-structure-info",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_SAVE_STRUCTURE_INFO",
                               CollectorInputType.BOOL, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/max-bulk-chunks",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_MAX_BULK_CHUNKS",
                               CollectorInputType.INT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/max-entity-collisions",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_MAX_ENTITY_COLLISIONS",
                               CollectorInputType.INT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/seed-village", "COLLECTOR_SPIGOT_WORLD_SETTINGS_SEED_VILLAGE",
                               CollectorInputType.INT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/seed-feature", "COLLECTOR_SPIGOT_WORLD_SETTINGS_SEED_FEATURE",
                               CollectorInputType.INT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/hunger/walk-exhaustion",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_HUNGER_WALK_EXHAUSTION",
                               CollectorInputType.FLOAT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/hunger/sprint-exhaustion",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_HUNGER_SPRINT_EXHAUSTION",
                               CollectorInputType.FLOAT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/hunger/combat-exhaustion",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_HUNGER_COMBAT_EXHAUSTION",
                               CollectorInputType.FLOAT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/hunger/regen-exhaustion",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_HUNGER_REGEN_EXHAUSTION",
                               CollectorInputType.FLOAT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/max-tnt-per-tick",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_MAX_TNT_PER_TICK",
                               CollectorInputType.INT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/max-tick-time/tile",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_MAX_TICK_TIME_TILE",
                               CollectorInputType.INT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/max-tick-time/entity",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_MAX_TICK_TIME_ENTITY",
                               CollectorInputType.INT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/item-despawn-rate",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_ITEM_DESPAWN_RATE",
                               CollectorInputType.INT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/merge-radius/item",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_MERGE_RADIUS_ITEM",
                               CollectorInputType.FLOAT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/merge-radius/exp",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_MERGE_RADIUS_EXP",
                               CollectorInputType.FLOAT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/arrow-despawn-rate",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_ARROW_DESPAWN_RATE",
                               CollectorInputType.INT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/view-distance", "COLLECTOR_SPIGOT_WORLD_SETTINGS_VIEW_DISTANCE",
                               CollectorInputType.INT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/chunks-per-tick",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_CHUNKS_PER_TICK",
                               CollectorInputType.INT, Version(1, 8, 0), LATEST_VERSION),
                CollectorInput("world-settings/default/clear-tick-list",
                               "COLLECTOR_SPIGOT_WORLD_SETTINGS_CLEAR_TICK_LIST",
                               CollectorInputType.BOOL, Version(1, 8, 0), LATEST_VERSION),
            ],
            "Warning: It's recommended to leave all these settings as default"
        ))
