import enum


class StatusCode(enum.Enum):
    """Class representing status code."""
    SUCCESS = enum.auto()

    IN_PROGRESS = enum.auto()

    PROGRESSBAR_UPDATE = enum.auto()
    PROGRESSBAR_NEXT = enum.auto()
    PROGRESSBAR_FINISH_TASK = enum.auto()
    PROGRESSBAR_END = enum.auto()

    INFO_VERSION_NEWER_THAN_SUPPORTED = enum.auto()
    INFO_JAVA_MINIMUM_21 = enum.auto()
    INFO_JAVA_MINIMUM_17 = enum.auto()
    INFO_JAVA_MINIMUM_16 = enum.auto()
    INFO_JAVA_MINIMUM_8 = enum.auto()
    INFO_LOCKER_MODIFIED = enum.auto()
    INFO_LOCKER_USING_REMOTE = enum.auto()
    INFO_LOCKER_UP_TO_DATE = enum.auto()
    INFO_LOCKER_UPDATING = enum.auto()

    ERROR_GENERIC = enum.auto()
    ERROR_JAVA_NOT_FOUND = enum.auto()
    ERROR_DOWNLOAD_SERVER_FAILED = enum.auto()
    ERROR_DOWNLOAD_INSTALLER_FAILED = enum.auto()
    ERROR_INSTALLER_NOT_FOUND = enum.auto()
    ERROR_JAVA_VERSION_DETECTION_FAILED = enum.auto()
    ERROR_SERVER_JAR_NOT_FOUND = enum.auto()
    ERROR_SERVER_SOURCE_NOT_SUPPORTED = enum.auto()
    ERROR_TEMPLATE_WRITE_FAILED = enum.auto()
    ERROR_TEMPLATE_NOT_FOUND = enum.auto()
    ERROR_TEMPLATE_MISSING_DATA = enum.auto()
    ERROR_TEMPLATE_INVALID_JSON_FORMAT = enum.auto()
    ERROR_TEMPLATE_READ_FAILED = enum.auto()
    ERROR_TEMPLATE_EXPORT_FAILED = enum.auto()
    ERROR_TEMPLATE_IMPORT_FAILED = enum.auto()
    ERROR_TEMPLATE_REFRESH_FAILED = enum.auto()
    ERROR_LOCKER_RETRIEVE_LATEST_TIMESTAMP_FAILED = enum.auto()
    ERROR_LOCKER_META_READ_FAILED = enum.auto()
    ERROR_LOCKER_META_UPDATE_FAILED = enum.auto()
    ERROR_LOCKER_DOWNLOAD_FAILED = enum.auto()
    ERROR_USERCONFIG_SAVE_FAILED = enum.auto()
    ERROR_USERCONFIG_READ_FAILED = enum.auto()
    ERROR_USERCONFIG_SET_FAILED = enum.auto()
    ERROR_USERCONFIG_REMOVE_FAILED = enum.auto()
    ERROR_USERCONFIG_CLEAR_FAILED = enum.auto()
    ERROR_USERCONFIG_LIST_FAILED = enum.auto()
    ERROR_USERCONFIG_KEY_NOT_FOUND = enum.auto()
    ERROR_USERCONFIG_FILE_NOT_FOUND = enum.auto()
    ERROR_CONFIG_PATH_INVALID = enum.auto()
    ERROR_CONFIG_PATH_NOT_WRITABLE = enum.auto()
    ERROR_CONFIG_FILE_WRITE_FAILED = enum.auto()
    ERROR_CONFIG_DIRECTORY_CREATE_FAILED = enum.auto()
    ERROR_CONFIG_VALIDATION_FAILED = enum.auto()
    ERROR_CONFIG_MISSING_REQUIRED_KEYS = enum.auto()
    ERROR_ASSEMBLER_NOT_FOUND = enum.auto()
    ERROR_CONFIG_ASSEMBLY_FAILED = enum.auto()
    ERROR_CONFIG_LINKING_FAILED = enum.auto()
    ERROR_SCRIPT_TEMPLATE_INVALID = enum.auto()
    ERROR_JAVA_FLAGS_GENERATION_FAILED = enum.auto()
