name: mcup
base: core22
version: '1.0.0-beta5'
summary: Command-line tool for quickly creating Minecraft servers
description: |
  Command-line tool for quickly creating Minecraft servers.

grade: stable
confinement: classic

apps:
  mcup:
    command: bin/mcup.sh

parts:
  mcup:
    plugin: dump
    source: .
    build-packages:
      - python3-pip
      - python3-venv
      - python3-dev
    stage-packages:
      - python3
      - python3-venv
    override-build: |
      python3 -m venv $CRAFT_PART_INSTALL/venv

      . $CRAFT_PART_INSTALL/venv/bin/activate
      pip install --upgrade pip
      pip install .
      
      mkdir -p $CRAFT_PART_INSTALL/bin
      install -Dm755 ./mcup.sh $CRAFT_PART_INSTALL/bin/mcup.sh
      
      cp -r . $CRAFT_PART_INSTALL/app