name: mcup
base: core22
version: '1.0.0-beta4'
summary: Command-line tool for quickly creating Minecraft servers
description: |
  Command-line tool for quickly creating Minecraft servers.

grade: stable
confinement: strict

apps:
  mcup:
    command: bin/mcup.sh
    plugs: [home, network]

parts:
  mcup:
    plugin: python
    source: .
    build-packages:
      - python3-pip
    override-build: |
      craftctl default
      install -Dm755 ./mcup.sh $CRAFT_PART_INSTALL/bin/mcup.sh
